### ISSUE TITLE
[BUG] Project is being captured as a dependency even though it is not

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#125]
**Describe the bug**
A project is wrongly captured as a dependency **when it starts with the same name as a project that is actually a dependency.**

**To Reproduce**
1. Create 3 projects (`dep-project`, `dep-project-foo`, `target-project`) 
libs/
├─ target-project/TargetProject.csproj
├─ dep-project-foo/DepProject.Foo.csproj
├─ dep-project/DepProject.csproj

2. Add `dep-project-foo` as a project reference in `target-project`
3. Run `nx dep-graph`
4. Not only is `dep-project-foo` a dependency of `target-project` but also `dep-project`

**Expected behavior**
`target-project` should only have one dependency: `dep-project-foo`

**Additional context**
I think the problem is here:
https://github.com/nx-dotnet/nx-dotnet/blob/3ca8a58536d24c0b496d76d370a5b70e7b3b139c/packages/utils/src/lib/utility-functions/workspace.ts#L74

Comparing against `` `${path}\\` `` appears to fix the issue.

**Comment by AgentEnder** [comment]
Yikes, yeah thats valid. I'd prefer something like this to make sure it doesn't break across OS's

```
import {normalizePath} from '@nrwl/devkit'
...
  if (normalizePath(workspaceFilePath).startsWith(`${path}/`)
...
```

@pemsbr Are you interested in putting a PR in for this? I can assign it to you if so 😄

**Comment by pemsbr** [comment]
Sure, I can pick it up 👍

**Comment by pemsbr** [comment]
I don't seem to have permissions to push my branch with the fix and create the PR

**Comment by AgentEnder** [comment]
You'll need to fork it and push your branch there to create the PR, this gist seems to document that flow well

https://gist.github.com/Chaser324/ce0505fbed06b947d962

There's a discussion thread that details how to test your changes locally somewhere around here.
