### ISSUE TITLE
[BUG] nx lint fails on dotnet project

### ISSUE THREAD

**Issue by dasco144** [nx-dotnet/nx-dotnet#179]
**Describe the bug**
The nx lint command fails on the dotnet project due to the `check` argument being removed in favour of `verify-no-changes` [here](https://github.com/dotnet/format/issues/1268#issuecomment-901291779)

**To Reproduce**
1. run nx lint on your dotnet project
2. the command runs and installs dotnet-format (latest version at time of writing 5.1.225507)
3. the command fails

**Expected behavior**
The command should run and not fail

**Screenshots**
![image](https://user-images.githubusercontent.com/10575019/136039372-26cfde8f-e1b1-4488-993b-da0e98a49661.png)

**Environment:**

- OS: Windows 10
- Browser: N/A
- Version: 1.4.2
- Affected Packages: nx-dotnet

**Additional context**
When manually running the same command with `check` replaced with `verify-no-changes`, it works as expected

**Comment by AgentEnder** [comment]
Yikes, I didn't expect that option to change. That seems like a breaking change for no good reason on the `dotnet` side of things. I'll work on this at some point, need to make sure it works with the older versions too.

Thanks for the report.
