### ISSUE TITLE
feat(core): Support for `nx test my-dotnet-app`

### ISSUE THREAD

**Issue by AgentEnder** [nx-dotnet/nx-dotnet#20]

**Comment by bcallaghan-et** [comment]
The option for `test-template` cannot be specified on the command line. When parsing the command-line arguments, the flag `--test-template` will be converted to the key `testTemplate` on the options object. The generator then checks `options['test-template']`, which will never contain a value. Consider the command `npx nx generate @nx-dotnet/core:app my-app --template console --language C# --test-template none`. The prompt asking which test template should be used is shown, even though the test template was specified in the arguments. The field used in the code and in the schema should be changed to `testTemplate` so the parsed value is correctly interpreted.

**Comment by AgentEnder** [comment]
Nice catch, I was not aware the argument would be transformed like that, though it does make sense. I'll get that updated tomorrow morning (hope to have the test executor then as well.)
