### ISSUE TITLE
Feature Request: Support scoped namespaces

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#21]
Currently, all applications and libraries are generated with the PascalCased version of the name given by the user, without any prefix or scoping. At minimum, I would like to see the organization name at the start of the project name/namespace, similar to the existing `npmScope` configuration used with JS libraries. For example, a library named `my-lib` with an `npmScope` of `my-org` should use the C# namespace `MyOrg.MyLib`.

Extending this idea further, it may be useful to have additional workspace-specific scopes as intermediate segments in the namespace. Using the Nrwl Airlines example, the library named `shell` within the `booking` scope would be named `Nrwl.Booking.Shell`.

These two goals could be accomplished by reading the `npmScope` property from `nx.json` and parsing the folder path used to create the library. Alternatively, the namespace could be specified by the user exactly as they want it, without any inference from the generator.

**Comment by AgentEnder** [comment]
Excellent spot. This also matches the pattern VS would use when adding files as far as the folder namespacing goes.

Thanks for the contribution!
