### ISSUE TITLE
[BUG] ProjectReference's under the Choose msbuild element are ignored

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#214]
**Is your feature request related to a problem? Please describe.**
`ProjectReference`'s under the [Choose](https://docs.microsoft.com/en-us/visualstudio/msbuild/choose-element-msbuild?view=vs-2019) msbuild element are ignored by the enforce-module-boundaries check.
```
<Choose>
  <When Condition="'$(UseA)' == 'true'">
    <ItemGroup>
      <ProjectReference Include="..\ProjectA.csproj"/>
    </ItemGroup>
  </When>
  <Otherwise>
    <ItemGroup>
      <ProjectReference Include="..\ProjectB.csproj"/>
    </ItemGroup>
  </Otherwise>
</Choose>
```

**Describe alternatives you've considered**
As a workaround, I'm currently setting the condition on the `ProjectReference`'s itself but this can become quite tedious if you also have multiple property groups under the `When` branches

**Comment by AgentEnder** [comment]
Why should these not be part of the module boundaries checks? If these are adding one or the other references to the project, than they _should_ be part of the boundaries.
