### ISSUE TITLE
[BUG] Default build options are incompatible with Nx incremental builds

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#240]
**Describe the bug**
Dotnet projects are built more than once in a single pass with incremental builds enabled. For example, consider a workspace with a .NET app A that depends on .NET lib B which in turn depends on .NET lib C. Running `nx build A` will produce the following chain of events.

1. Nx builds project C
    1. dotnet builds project C
2. Nx builds project B
    1. dotnet builds project C
    2. dotnet buidls project B
3. Nx builds project A
    1. dotnet builds project C
    2. dotnet builds project B
    3. dotnet builds project A 

**To Reproduce**

1. Create a new Nx workspace
2. Add a dotnet app "A" to the workspace
3. Add two dotnet libs "A"  and "B" to the workspace
4. Add a reference from "A" to "B" and from "B" to "C"
5. Run `nx build A`

**Expected behavior**
With incremental builds, it is expected that `nx run-many --target build --all` will build each project only once and that `nx build my-app` will build `my-app` and each of its dependencies only once each.

**Environment:**

- OS: Windows
- Browser: N/A
- Version: 1.5.1
- Affected Packages: core

**Additional context**
The cause is related to the `output` option of the generated build target. This option tells dotnet that the generated build output should be placed in the specified directory, but it also tells dotnet that the generated build output of all dependent projects should also be placed in that directory. When dotnet goes to build the root project, it finds that none of the dependencies exist there, since they each got built and output into their own directories. If the `output` option is removed entirely, dotnet falls back on the directory specified in the .csproj files and correctly places each project into its own output folder.

This behavior is emphasized when using the `no-dependencies` option, which would give Nx exclusive control over how dependencies are built. With this option enabled, dotnet throws an error and fails to compile any project, since the dependencies don't exist in the app's output folder and it was instructed not to compile the dependencies.

**Comment by AgentEnder** [comment]
Hey, I discussed this a bit on the NX community slack here (https://nrwlcommunity.slack.com/archives/C017QSST318/p1634751205054800?thread_ts=1634333090.036900&cid=C017QSST318).

I would really like to get this working, but unfortunately have been rather busy as of late... I'd love for --no-dependencies to work, theoretically all that would be needed is a part of the executor that runs before the .NET commands. Something like

```
export buildExecutor(...) {
    if (opts.noDependencies) {
      forEachNxDotnetProjectDependency((dep) => {
          copyBuildDllToExpectedLocation(dep, project)
      })
    }
   // ... existing logic
}
```
