### ISSUE TITLE
[Feature] Search for dependencies in `.cs` files (`usings`)

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#276]
**Describe the solution you'd like**
Apart from searching for dependencies in `.csproj` files, nx-dotnet should also check for usings in `.cs` files.

**Describe alternatives you've considered**

**Additional context**
[Global using directives](https://devblogs.microsoft.com/dotnet/announcing-net-6/#global-using-directives) (introduced in C# 10) should also be taken into consideration.

**Comment by AgentEnder** [comment]
Is it possible to introduce a new project dependency w/o updating the `.csproj` file? I thought that was still necessary, and given that it wouldn't make sense to introduce the complexity of walking the source tree

**Comment by pemsbr** [comment]
You're right, I think we can ignore this.
