### ISSUE TITLE
[BUG] Serve target should not be generated for libraries

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#28]
**Describe the bug**
When generating a library, the newly-added section of `workspace.json` includes a `serve` target. This target invokes `dotnet run` under the hood, which is not supported for library projects. The `serve` target should only be added to application projects.

**To Reproduce**
1. Create a new Nx workspace
2. Generate a new class library with `npx nx generate @nx-dotnet/core:lib my-lib --template classlib --language C#`
3. Open `workspace.json` and find the section for `my-lib`.
4. The `architect` key includes a `serve` target, which will always fail when run.

**Expected behavior**
A `serve` target should not be included for library projects. Only the `build` target should be scaffolded (plus a `test` target if a test template was specified).

**Environment:**
 - OS: Windows
 - Browser: N/A
 - Version: 0.2.0
 - Affected Packages: `@nx-dotnet/core`

**Comment by AgentEnder** [comment]
This should be fixed in generate-project.ts. Bug was introduced when the logic was removed from the individual generators. Feel free to open a PR or I will get to it tomorrow sometime.

**Comment by AgentEnder** [comment]
@all-contributors add @bcallaghan-et for code
