### ISSUE TITLE
[Security] Workflow main.yml is using vulnerable action bahmutov/npm-install

### ISSUE THREAD

**Issue by qazaqstan2025** [nx-dotnet/nx-dotnet#299]
The workflow main.yml is referencing action bahmutov/npm-install using references v1.4.5. However this reference is missing the commit [7e73ecd0864000ec1a8f86106d73e38c09dbaca3](https://github.com/bahmutov/npm-install/commits/7e73ecd0864000ec1a8f86106d73e38c09dbaca3) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by AgentEnder** [comment]
This commit was only updating a dev dependency (https://github.com/bahmutov/npm-install/pull/61/files), and a version w/ the update has not been released. Since dev dependencies do not affect the actual runtime of the action, this update will not be made until an actual release has been published.
