### ISSUE TITLE
[Feature] Executor to publish web apps

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#33]
**Is your feature request related to a problem? Please describe.**
My application projects have a "Publish Profile" generated by Visual Studio 2019. These files can be used with the `dotnet publish` command to deploy production-ready executables to the configured target (local folder, IIS, Azure, etc.). I would like to execute this command through Nx to enable a CI/CD workflow that includes `nx affected --target=deploy`.

**Describe the solution you'd like**
A new executor that simply wraps the `dotnet publish` command will be sufficient for the desired workflow. It should be very similar to the existing `build` executor. It should also be able to pull configuration from the environment, such as deployment credentials.

**Describe alternatives you've considered**
The Nx `run-commands` executor allows for the basic construction of the `dotnet publish` command, but the variability of the arguments was too much to encode into the `workspace.json` file.

**Additional context**
I have previously worked on a similar feature for my workspace's private use. Deployment secrets were handled by allowing shell syntax in the executor's configuration, and then using environment variables as the properties' values. For example,
```json
"options": {
  "PublishProfile": "MyPublishProfile",
  "UserName": "%MY_USR%",
  "Password": "%MY_PSW%"
}
```
In general, there may be more than one Publish Profile, and deployment credentials may be needed to connect to a remote machine.

**Comment by AgentEnder** [comment]
Something like this is a no-brainer to add, especially for things like `nx affected deploy`. 

If you feel comfortable putting together a PR we can assign this to you, otherwise I will get to it sometime in the next two weeks or so.

Like you said the build or test executor are great starting points.

**Comment by bcallaghan-et** [comment]
I started a branch for this, and I have all of the normal flags done. I'm trying to decide how the MSBuild properties should be handled. Flags like Publish Profile and User Name appear as `-p:PublishProfile=MyProfile` and `-p:UserName=MyName`. Note that they only have one dash, they have the `p:` prefix, and they use an explicit equals sign to denote the value. I'm leaning towards including the prefix in the json file, and then adding that prefix as a special case to the `getParameterString` function. For example,
```json
"options": {
  "configuration": "Release",
  "p:PublishProfile": "MyProfile"
}
```
becomes
```sh
dotnet publish --configuration Release -p:PublishProfile=MyProfile
```
The downside to this method is that the MSBuild properties can't be specified on the command line.

Alternatively, the MSBuild properties could be held in a sub-object that has its own encoding rules, and the key containing that object is handled separately within `getParameterString`.

**Comment by AgentEnder** [comment]
I would add a special case for publish profile, so that it shows up in the schematic options. Schematic options would be each of the individual options listed on msdn for `dotnet publish`, with the additional option `publishProfile` and an option called "extraParameters" That would just take a string and could be appended to the end of the command within DotNetClient.
