### ISSUE TITLE
[BUG] `ProjectReference`s with glob patterns are ignored

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#335]
**Describe the bug**
`ProjectReference`s with glob patterns are ignored.

**To Reproduce**
1. Create 3 projects (`target`, `deps/dep-1`, `deps/dep-2`) 
libs/
├─ target/Target.csproj
├─ deps/dep1/Dep1.csproj
├─ deps/dep2/Dep2.csproj

2. Set projects under `deps` as project references in `target`
```xml
<ProjectReference Include="../deps/**/*.csproj" />
```
3. Run `nx dep-graph`
4. `target` has no dependencies

**Expected behavior**
Glob patterns should work as expected

**Additional context**
MSBuild properties also don't work, e.g.:
```xml
<ProjectReference Include="$(PropertyWithPath)/Project.csproj" />
```

**Comment by AgentEnder** [comment]
I honestly didn't know the glob patterns were an option 🤷. We should probably move to using `dotnet list reference` instead of parsing the xml files for projects, especially with the daemon being the default for Nx I'm not too worried about the perf penalties.
