### ISSUE TITLE
[BUG] Argument forwarding not working as expected

### ISSUE THREAD

**Issue by pemsbr** [nx-dotnet/nx-dotnet#336]
**Describe the bug**
Argument forwarding not working as expected.

https://nx.dev/workspace/run-commands-executor#arguments-forwarding
> This is useful when you need to pass raw argument strings to your command.

The command:
```console
nx serve project --watch=false --args="-- verb --param1=arg1 --param2=args"
```
is invoking:
```console
dotnet run --project Project.csproj --configuration Debug --args -- verb --param1=arg1 --param2=args
```
instead of:
```console
dotnet run --project Project.csproj --configuration Debug -- verb --param1=arg1 --param2=args
```

**Expected behavior**
The `args` option should allow passing raw strings to the command.

**Additional context**
Fixing this would also close #295

**Comment by asinino** [comment]
This is possible duplication of #262, though the explanation here completes the other ticket.

**Comment by AgentEnder** [comment]
The `--args` options here is specific to nx:run-commands, its not something currently provided on the executors we provide. I'd be open to PRs adding them where necessary, although I think `extraParameters` may fit the same slot.
