### ISSUE TITLE
[BUG] test suites are included in the NPM package

### ISSUE THREAD

**Issue by LayZeeDK** [nx-dotnet/nx-dotnet#34]
**Describe the bug**
`*.spec.ts` files are included in the `@nx-dotnet/core` package. I noticed them for the generators.

**To Reproduce**
1. `npm install --save-dev @nx-dotnet/core`
2. Look in `node_modules/@nx-dotnet/core/(...)`

**Expected behavior**
No test suites are included in an NPM package.

**Environment:**
- Version: 0.4.1 
- Affected Packages: `@nx-donet/core`

**Comment by AgentEnder** [comment]
This should be fixed in the next patch version, but is an issue within the Nx plugin generator by default.

I created nrwl/nx#5563 to handle this.

**Comment by AgentEnder** [comment]
Associated PR in @nrwl/nx has been merged.
