### ISSUE TITLE
[BUG] Test and format executors don't work with Nx VSCode extension

### ISSUE THREAD

**Issue by lourd** [nx-dotnet/nx-dotnet#363]
**Describe the bug**
When trying to run the `test` or `format` executors from `@nx-dotnet/core` using the [Nx Console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) extension for VSCode, it fails with the error "Builder specified for {project name} {command} was not found in your dependencies. Check that specified builder is correct and has a corresponding entry in package.json.

@nx-dotnet/core is in fact listed in my package.json and installed, and running the command from my terminal works as expected.

**To Reproduce**

1. Generate a C# library using @nx-dotnet
2. Set up a target in that library's `project.json` that uses either `@nx-dotnet:test` or `@nnx-dotnet:format`. For example:
    
    ```
    "lint": {
      "executor": "@nx-dotnet/core:format"
    }
    ```
3. Run the target using the Nx Console extension, either by clicking on the command that shows up in the `project.json` file, or using the command palette — Nx: run > {library name} > lint

**Expected behavior**
The command runs like normal, which it does now if I run it from the command line.

**Screenshots**
![Screen Shot 2022-02-15 at 12 33 52 PM](https://user-images.githubusercontent.com/2012388/154118055-ca9e3d9c-4281-4d39-b816-03d89569ef67.png)

**Environment:**

- OS: macOS 12.1
- Browser: n/a
- Version: @nx-dotnet/core@1.8.0, Nx Console v17.14.1, nx@13.2.3

**Comment by AgentEnder** [comment]
Can you check the output panel in vscode and see if more info is available?

**Comment by AgentEnder** [comment]
This looks like it may be an issue on Nx Console's side of things. I'll open an issue there. In the meantime, running the executors from the panel instead of codelens or command palette will work through nx console today, or just using the CLI either way as a workaround.

**Comment by AgentEnder** [comment]
This should be fixed in the next Nx console release, since it has been merged. Going to close this now.
