### ISSUE TITLE
Dependency Graph not being correctly generated

### ISSUE THREAD

**Issue by YasserKharab** [nx-dotnet/nx-dotnet#381]
Just started using nx-dotnet and having issues with dep-graph 

**To Reproduce**
Just created a new workspace with two dotnet libs (lib1 ref lib2)
generate the workspace: `npx create-nx-workspace@latest`
choose template: apps
install nxdotnet: `npm i --save-dev @nx-dotnet/core`
create lib1 and lib2 
add reference from lib1 to lib2 
build everything: `npx nx run-many --target=build --all `
generate dep-graph: `nx dep-graph`
result:
![image](https://user-images.githubusercontent.com/97306965/156046415-3ed2acab-b8c1-4163-9583-39ef6a2eda10.png)
also the lib1.csproj inside .cashe\nx\nxdeps.json doesn't contain any "deps" node

**Expected behavior**
nxdeps.json should contain the deps for each csproj
![image](https://user-images.githubusercontent.com/97306965/156046776-536bd7ea-31a9-450a-875f-3e9b00c96075.png)

**Comment by AgentEnder** [comment]
Can you run `nx report` and also check that '@nx-dotnet/core' is listed as a plugin in `nx.json`?

**Comment by YasserKharab** [comment]
Yes i do have  "plugins": ["@nx-dotnet/core"] under nx.json

results for `nx report`

   Node : 16.3.0
   OS   : win32 x64
   npm  : 7.18.1

   nx : 13.8.3
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.3
   @nrwl/cypress : undefined
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : undefined
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : undefined
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.5
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : undefined
   @nrwl/tao : 13.8.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 6.5.5
   ---------------------------------------
   Community plugins:
         @nx-dotnet/core: 1.9.2
