### ISSUE TITLE
Dependency Graph not working when adding angular lib

### ISSUE THREAD

**Issue by YasserKharab** [nx-dotnet/nx-dotnet#389]
After the fix related to 381, right now the following Exception is being thrown when adding an Angular lib or App to the workspace

**To Reproduce**
Just created a new workspace with two dotnet libs (lib1 ref lib2)
generate the workspace: `npx create-nx-workspace@latest`
choose template: apps
install nxdotnet: `npm i --save-dev @nx-dotnet/core`
add Angluar to nrwl: `npm install --save-dev @nrwl/angular`
create lib1 and lib2
add reference from lib1 to lib2
create anglib (Angular library)
generate dep-graph: `nx dep-graph`

results:
![image](https://user-images.githubusercontent.com/97306965/156241930-b5ed4a82-aed9-45c6-a215-9c924cf6ce46.png)

Exception at: 
![image (1)](https://user-images.githubusercontent.com/97306965/156242054-04af1467-9c9a-40f0-9f1e-1adab8c09bea.png)

Note: moving the all angular projects down the list in the workspace.json will make the dep-graph render correctly as the exception will be thrown last.

**Environment:**

   Node : 16.3.0
   OS   : win32 x64
   npm  : 7.18.1

   nx : 13.8.3
   @nrwl/angular : 13.8.3
   @nrwl/cli : 13.8.3
   @nrwl/cypress : 13.8.3
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.3
   @nrwl/eslint-plugin-nx : 13.8.3
   @nrwl/express : undefined
   @nrwl/jest : 13.8.3
   @nrwl/js : undefined
   @nrwl/linter : 13.8.3
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : 13.1.6
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.3
   @nrwl/tao : 13.8.3
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.3
   typescript : 4.5.5
   rxjs : 7.4.0
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.2.4
         @angular/common: 13.2.4
         @angular/compiler: 13.2.4
         @angular/core: 13.2.4
         @angular/forms: 13.2.4
         @angular/platform-browser: 13.2.4
         @angular/platform-browser-dynamic: 13.2.4
         @angular/router: 13.2.4
         @angular-devkit/build-angular: 13.2.5
         @angular/cli: 13.2.5
         @angular/compiler-cli: 13.2.4
         @angular/language-service: 13.2.4
         @nx-dotnet/core: 1.9.3

**Comment by AgentEnder** [comment]
Ah, drat. I see why, we used to have a tag (NX_DOTNET) that marked a project as belonging to the plugin. Then we only dealt with our analysis for projects with that tag. This doesn't work with project inference, so we dropped the reliance on the tag.

However, this function was missed evidently. It definitely throws if the directory doesn't contain a .NET project. I'll push an update out soon.

**Comment by MasroorSyed-Tag** [comment]
@AgentEnder what version of nx-dotnet can we roll back to make it work?

**Comment by AgentEnder** [comment]
I think 1.8.0 should be fine, as long as you are not using project inference.
