### ISSUE TITLE
[BUG] Version of dotnet format included in SDK version 6/7 is broken

### ISSUE THREAD

**Issue by asinino** [nx-dotnet/nx-dotnet#394]
**Describe the bug**
I have `dotnet-format` V5.1.250801 installed globally, when I try to lint a project it fails.
I tried to get a changelog on the `dotnet-format` page but there are missing changelogs from version v5.1.225507 to V5.1.250801, need to see undercover to see what is the replacement.

**To Reproduce**

1. `dotnet tool install --global dotnet-format --version 5.1.250801`
2. `cd $SLN_DIR`
3. `nx lint app123`
4. --See error--

The package `dotnet-format` fails to process the project but the `nx lint` command finishes with success, and maybe because of this e2e tests are running fine.

**Expected behavior**
Lint commands finish with success.

**Screenshots**
![image](https://user-images.githubusercontent.com/32019405/156729017-5fe12ba1-f0d1-4e61-b70f-958f702d9578.png)

**Environment:**

- OS: Windows 10
- Version; 1.9.4

**Additional context**
On version 1.9.5 the command does not use the attribute `--check` but it still ends with a different error (on both versions of @nx-dotnet/core I created a new workspace, both with the same dotnet-format version):

![image](https://user-images.githubusercontent.com/32019405/156731416-71206aae-5a56-44a3-9c86-3856c47a6414.png)

Should I create a new issue for this version? It's obvious that something changed between V1.9.4 and V1.9.5 for this command.

**Comment by AgentEnder** [comment]
@asinino  looking at the v1.9.5 screenshot, it looks like its working correctly for you, but the actual `dotnet format --verify-no-changes` command is failing with the error. Can you try invoking the command directly from command line rather than through Nx to see if its a project issue?

**Comment by AgentEnder** [comment]
In .NET SDK v6 they inlined the `dotnet-format` tool into the SDK but made some breaking changes such as using `--verify-no-changes` instead of `--check`. The version of the SDK matters, the version of the tool doesn't

**Comment by asinino** [comment]
I started a new one using only dotnet 6 (previously I was using 5), using the next steps:

```shell
npx create-nx-workspace@latest
npm i --save-dev @nx-dotnet/core
npx nx g @nx-dotnet/core:init

nx g @nx-dotnet/core:application --name=app123 --template=webapi --language=C# --testTemplate=nunit
nx lint app123
```

Running the `dotnet format` alone bugs out with the same error, maybe is something wrong with their format tool?

I've created a new project only using dotnet 6 SDK, with the steps:

```
dotnet "new" "webapi" "--language" "C#" "--name" "Company.App123" "--output" "MyApp"
dotnet "format" "MyApp/Company.App123.csproj" "--verbosity" "minimal" "--verify-no-changes"
```

I get the same error, so it's not @nx-dotnet. But maybe the lint command should fail, if we have this as part of our commit or CI process it should cancel the next commands.

**Comment by asinino** [comment]
So I was digging on dotnet-format repository issues and definitely, this is an issue on their package and there isn't still a fix released, this only happens on `dotnet format` not in the tool command with a hyphen `dotnet-format`.

There isn't an ETA available yet.

**Option 1:**

Should we provide a quirk that temporarily (until the fix is released, we verify version > 6 and version < 6.0.3 or fixed version) we call the `dotnet-format` and user must have [dotnet-format] installed globally? (must say that on version 6 we do not need to install this package, it is built in the dotnet directly).

**Option 2:**

Close this issue, dotnet-format package will fix this in a future version, until then no one will be able to use this tool on our package, so we temporarily can't guarantee that users commit correctly formatted code.

@AgentEnder What do you think about this?

**Comment by AgentEnder** [comment]
@asinino I added a workaround in the linked PR, taking something closer to option 1 but installing the tool locally. Do you care to review the changes?

**Comment by asinino** [comment]
Better than my solution, we let a port open for future problems, we just have to signal if we have a problem.
