### ISSUE TITLE
[Feature] Allow forwarding parameters from c# custom templates

### ISSUE THREAD

**Issue by JayArrowz** [nx-dotnet/nx-dotnet#398]
**Is your feature request related to a problem? Please describe.**
When i make a new template using: https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template

If i add template arguments/params `--functionName` as shown in the guide here: https://github.com/dotnet/templating/wiki/Reference-for-template.json

![image](https://user-images.githubusercontent.com/49910176/157998851-a9e3b584-2d94-470a-976f-612f0e1bab52.png)

However the --functionName does not get forwarded to the `dotnet new` command:
![image](https://user-images.githubusercontent.com/49910176/157998886-3f85ae92-a25e-41a7-a8ce-2c64775feed8.png)

**Describe the solution you'd like**
Allow argument forwarding to `dotnet new` command

**Describe alternatives you've considered**
Have no arguments, but then this blocks a huge template functionality

**Comment by Nozemi** [comment]
Also to add to this issue; https://www.nx-dotnet.com/docs/core/generators/application

Each of the options for `nx-dotnet/core:application` are explained, and the `template`-option, even mentions some templates might have specific options you can pass. It doesn't tell us how to pass anything. If it was as obvious as in the command from the screenshot above, I'd agree not explaining it further.

**Comment by JayArrowz** [comment]
@AgentEnder hi is there any updates on this pls?

**Comment by balloman** [comment]
Are there any updates to this? No feedback, nothing?

**Comment by AgentEnder** [comment]
Implementation wise this should read from unparsed, find anything after --, and pass those as is into the call to dontetClient.new. this would probably be a new argument called "extraParameters" or similar, optional and defaults to an empty string or array. A few other methods in that class already have similar parameters.

I'm open to a PR that implements the above, I've just not had time to do so myself.

**Comment by balloman** [comment]
> Implementation wise this should read from unparsed, find anything after --, and pass those as is into the call to dontetClient.new. this would probably be a new argument called "extraParameters" or similar, optional and defaults to an empty string or array. A few other methods in that class already have similar parameters.
> 
> An example of reading unparsed args in an executor: https://github.com/nrwl/nx/blob/master/packages/nx/src/executors/run-commands/schema.json#L129
> 
> I'm open to a PR that implements the above, I've just not had time to do so myself.

Why prefer this option over adding a property called like args that accepts a string, similar to the args property on the run-commands executor?

**Comment by AgentEnder** [comment]
Using something like --args is harder on the end user. Consider:

```
nx g app myapp --template test --args "--arg1=\"t\" --arg2=\"v\""
```

Vs

```
nx g app myapp --template test -- --arg1="t" --arg2="v"
```

**Comment by balloman** [comment]
Hmm, makes sense, but then with this way, the UI would be unusable with this option right? In any case, I should have a PR open later today for this.
