### ISSUE TITLE
[BUG] Can't use VS Code NX Console to reference a project library or a NuGet package

### ISSUE THREAD

**Issue by asinino** [nx-dotnet/nx-dotnet#405]
**Describe the bug**
When using the VSCode NX Console plugging I can not add a reference to a project or a reference to a NuGet package, the command generated is missing the attributes' names.

**To Reproduce**
Steps to reproduce the behavior: see the images below, the example uses minimal parameters to have success but if we fill up other parameters they have the same problem.

![image](https://user-images.githubusercontent.com/32019405/161009266-a44c0002-97ca-43d4-9ba1-13d165a1ec64.png)

![image](https://user-images.githubusercontent.com/32019405/161009595-7f7a0c60-708e-40e4-8c50-08f142cf2db8.png)

**Expected behavior**
Reference a project library or a NuGet package using the VS Code NX Console plugin.

**Environment:**

- OS: Windows 10
- Version: 1.9.7

**Comment by AgentEnder** [comment]
Hey @asinino! It looks like this is actually an issue with Nx console, it must not handle multiple positional parameters well. I'm going to file an issue there and then link it here.
