### ISSUE TITLE
[Feature] add a new `move` generator to @nx-dotnet/core

### ISSUE THREAD

**Issue by AgentEnder** [nx-dotnet/nx-dotnet#406]
**Is your feature request related to a problem? Please describe.**
`.csproj` files contain relative paths to any other projects in the repo that they reference

**Describe the solution you'd like**
These paths are updated during the move generator such that you can move a project from the command line without breaking other projects.

**Additional context**
`dotnet` doesn't support any kind of path aliases, so these have to be relative.

**Comment by bcallaghan-et** [comment]
Thinking out loud here: the generator would need to do the following.

1. Move the project's files to the new directory
2. Update the `.csproj` of every project that references the moved project.
3. Update the `root`/`sourceRoot` properties `project.json`/`workspace.json` of the moved project
4. Update the path within `workspace.json` (if using separate `project.json` files)
5. Update the `.csproj` name to match the new directory
6. Update the namespace of every `.cs` file in the moved project
7. Update the `using`s of every `.cs` file that references the now-renamed namespaces

Steps 1-4 seem simple enough. Steps 5-7 are much harder, and would normally be accomplished through refactoring tools like Visual Studio or ReSharper.

**Comment by AgentEnder** [comment]
A minimalist version of the generator could only do steps 1-4 and be "done", later we could enhance it with the refactoring / ast work.

For steps 1-4, you'd just call through to the regular Nx move and then after calling it youd need to handle the csproj name changes

**Comment by AgentEnder** [comment]
I don't think so, since the regular Nx move generator doesn't. It could be added perhaps, but I'm not sure how I'd design it in terms of schema

**Comment by bcallaghan-et** [comment]
Two other things this generator might need to do

1. Update the solution folder path (when used with a Visual Studio solution)
2. Update the Nx project name (which currently contains the relative path of the project). For example, moving a project from `libs/billing/api` to `libs/shipping/shared` would rename the project from `billing-api` to `shipping-shared`.

**Comment by AgentEnder** [comment]
2 should be done when invoking nrwl/workspace:move, so I wouldn't worry about it. 1 is definitely something we'd need to handle.

**Comment by bcallaghan-et** [comment]
So you plan on using `@nrwl/workspace:move` do some of the heavy lifting? I wasn't sure if we could re-use the logic from that generator.

**Comment by AgentEnder** [comment]
I'd let it do **_as much as possible_**. The only parts we should be doing is updating file contents after the relocation

**Comment by bcallaghan-et** [comment]
The existing `@nrwl/workspace:move` generator crashes when used with an nx-dotnet project.
```sh
> Executing task: npx nx generate @nrwl/workspace:move new --projectName=old-common --no-updateImportPath --no-interactive --dry-run <


>  NX  Generating @nrwl/workspace:move


 >  NX   unable to find "@etogy-test/old/common" in tsconfig.base.json compilerOptions.paths

   Pass --verbose to see the stacktrace.

The terminal process "C:\Program Files\Git\bin\bash.exe '-c', 'npx nx generate @nrwl/workspace:move new --projectName=old-common --no-updateImportPath --no-interactive --dry-run'" terminated with exit code: 1.
```

I tried with and without the `--no-updateImportPath` flag. If I add the following to `tsconfig.base.json`, then the generator completes as normal.
```json
"paths": {
  "@etogy-test/old/common": []
}
```

**Comment by AgentEnder** [comment]
That's interesting 🤔, on the Nx side we should update that then... I'll add a backlog item, should be a quick change to make it work without tsconfig path

**Comment by AgentEnder** [comment]
Feel free to deep import the utils that the workspace move generator uses in the meantime

**Comment by AgentEnder** [comment]
For reference I settled on a simple generator for now that handles some, but not all of this.

Currently the generator:
- moves files
- renames the nx project
- updates any strings in the project configuration that contained the old path (e.g. sourceRoot)
- updates any project or solution files that contained a reference to it

**Comment by AgentEnder** [comment]
Notably, the current implementation **_does not_** rename namespaces
