### ISSUE TITLE
[Feature] Replace glob with fast-glob for .*proj file search in project-graph calculation

### ISSUE THREAD

**Issue by johannesf95** [nx-dotnet/nx-dotnet#410]
**Is your feature request related to a problem? Please describe.**
When trying to introduce nx with nx-dotnet to a large existing solution with about 70 projects, I figured out that the project graph calculation took several minutes. By debugging the nx-dotnet plugin I found out that the glob search for .*proj files took about 3 minutes, due to the fact that I did not use the nx dist dir as output directory but the normal bin directory within the project directory to avoid to much changes to the repository structure and build architecture for now. 

**Describe the solution you'd like**

1. By replacing glob with fast-glob locally, I was able to reduce the execution time of the project-graph calculation from ~3 Min. to 30 Sec. So I would like to suggest using fast-glob which is used by nx as well.
2. Optionally: By passing the ignore option to glob / fast-glob like: `['**/bin/**', '**/obj/**']`, it is possible to speed up the calculation even more: fast-glob took 15 Sec. whereas glob took ~35 Sec. 

**Describe alternatives you've considered**
Changing the output directories to the normal nx dist directory could be an option to speed up the execution, but that would possibly interfere with our current build architecture and would cause more concerns from some developers against introducing nx workspace.

**Comment by AgentEnder** [comment]
Sounds good to me. Do you care to throw a PR together for this? If you've done it locally, it shouldn't be too much trouble. Use the same version of fast-glob we use in Nx; there are some regression bugs in the latest version.

**Comment by johannesf95** [comment]
Sure, will try to open a PR tomorrow! 👍

**Comment by AgentEnder** [comment]
Regardless of the swap to fast glob, we should do option 2 eventually as well. Nx does this during project inference, but we should adhere to it as well.
