### ISSUE TITLE
[BUG] Tests fail when run with the --skip-cache flag

### ISSUE THREAD

**Issue by bcallaghan-et** [nx-dotnet/nx-dotnet#42]
**Describe the bug**
When using the Nx flag `--skip-cache`, all dotnet tests fail with the following error.
```
MSBUILD : error MSB1001: Unknown switch.
Switch: --skipCache
```

**To Reproduce**

1. Create a new Nx workspace.
2. Create a new app with a test project using `nx generate @nx-dotnet/core:app --name=app --language=C# --template=console`.
3. Run the (empty) test project with `nx run app-test:test --skip-cache`.
4. The tests will fail with the above error.

**Expected behavior**
The tests should run normally, and the Nx cache is not used to replay old results.

**Environment:**

- OS: Windows
- Browser: N/A
- Version: 0.5.1
- Affected Packages: @nx-dotnet/core

**Additional context**
I am somewhat surprised that the `--skip-cache` flag is being passed to the executor, as it is an Nx flag and not an executor option. The intention is to run the tests without checking the cache for a previous run. This may be a bug with Nx that the global flag is being passed to all executors. If this behavior is intended, then the dotnet plugin will need to exclude the `skipCache` option when generating the dotnet client flags.

**Comment by AgentEnder** [comment]
Hey @bcallaghan-et . I believe the flag you are looking for is `--skip-nx-cache`, not `--skip-cache`

**Comment by bcallaghan-et** [comment]
/facepalm Yep, that was the command I wanted. With the correct flag, the plugin works fine and all tests run.
