### ISSUE TITLE
linting failing

### ISSUE THREAD

**Issue by YasserKharab** [nx-dotnet/nx-dotnet#423]
dotnet projects linting is failing in last version (1.9.11), running dotnet-format commands works correctly though.
replacing the lint node under the project.json as follow works as well:
```
"lint": {
      "executor": "@nrwl/workspace:run-commands",
      "options": {
        "commands": [
          "dotnet-format \"path to csproj" --verbosity minimal --verify-no-changes"
        ]
      }
    }
  },
```
default node fails: 
```
    "lint": {
      "executor": "@nx-dotnet/core:format"
    }
```
with error: /home/runner/work/**
Executing Command: dotnet "tool" "run" "dotnet-format" "path to .csproj" "--verbosity" "minimal" "--verify-no-changes"
dotnet execution returned status code 1

**Comment by AgentEnder** [comment]
There should be additional logging above the error message, do you see any? What version of .NET SDK is running?

**Comment by YasserKharab** [comment]
running dotnet 6.0.202
the error above is the only detail in nx cloud, in console though it's asking to run "dotnet tool restore", 
![image](https://user-images.githubusercontent.com/97306965/164744968-57194486-e49f-4adf-ae42-57b01407d2ef.png)

**Comment by AgentEnder** [comment]
In `package.json` do you have the post-install restore hook?

**Comment by AgentEnder** [comment]
During `npm run prepare`, it should run tool-restore. See here:

https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/core/src/generators/restore/generator.ts#L22
https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/core/src/generators/init/generator.ts#L82

**Comment by YasserKharab** [comment]
> In `package.json` do you have the post-install restore hook?

No, using Husky instead, will try to add it in package.json

**Comment by YasserKharab** [comment]
> In `package.json` do you have the post-install restore hook?

No, will try to add it in package.json

**Comment by YasserKharab** [comment]
Sorry for delay, guess this has fixed the issue but i am adding the restore script "nx g @nx-dotnet/core:restore" inside the package.json prepare hook manually, any idea on how this get called ? https://github.com/nx-dotnet/nx-dotnet/blob/507e17ab411d8b7fbeb1df1f54baca3deda2f559/packages/core/src/generators/init/generator.ts#L13

**Comment by AgentEnder** [comment]
The generator should be called anytime you generate an app / lib with nx-dotnet, but that specific function is only called when you don't yet have an nx dotnet config file.

I'm going to close this out since the issue seems to not crop up from a standard flow, and since its been fixed for your use case. Thanks @YasserKharab
