### ISSUE TITLE
Management of locally installed dotnet tools

### ISSUE THREAD

**Issue by AgentEnder** [nx-dotnet/nx-dotnet#44]
I definitely agree about installing tools being the path for getting this executor up and running. 

I see something like this:
1. Init schematic is updated to create the tool-manifest, with some messaging about "Tool Manifest created for managing dotnet tools"
2. Tools are installed if needed at the time a schematic that would use them is used the first time.
    * In practice, this means that we can have this format tool, or the swagger cli tool later, or other tools be known by the package, but only installed if users care about them.
    * A process flow with this would look something like: User runs `nx format my-api` -> Executor checks for tool in manifest, installs if missing -> Executor checks that tool has been restored, reports error message otherwise -> Executor runs tool
3. Add a restore schematic (simple schematic, runs `dotnet restore` and `dotnet tool restore`)
4. Update init schematic to add `nx g @nx-dotnet/core:restore` to npm prepare scripts. Something like:
    ```typescript
        const package = readJson(host, 'package.json')
        const prepareSteps = package.scripts.prepare?.split?.('&&')?.map?.(x => x.trim()) ?? [];
        if (!prepareSteps.includes('nx g @nx-dotnet/core:restore')) {
            prepareSteps.push('nx g @nx-dotnet/core:restore')
        }
        package.scripts.prepare = prepareSteps.join(' && ')
        writeJson(host, 'package.json', package)
    ```

I'll create new issues for the tool management when I am home this evening.

After we get tool-mgmt in, this executor should be pretty quick to test.

_Originally posted by @AgentEnder in https://github.com/nx-dotnet/nx-dotnet/issues/13#issuecomment-842633817_

**Comment by bcallaghan-et** [comment]
@AgentEnder I can start working on this today. The steps you've laid out are enough to get me started.

**Comment by AgentEnder** [comment]
@bcallaghan-et Make sure to extract the steps for checking if tool is in manifest + checking if tools have been restored to utilities so they are easy to use from other generators.

**Comment by bcallaghan-et** [comment]
When a tool is installed locally, the binaries are cached in a global location, and the version number is noted in the local manifest file. If the same tool is re-installed, the cached binaries are used. Would it be acceptable to "install" the tool every time, rather than checking if it has been installed?

**Comment by AgentEnder** [comment]
As long as the cached binary is used instead of deleting and reinstalling I am good with that.
