### ISSUE TITLE
[Feature] Enable support for Azure Functions projects

### ISSUE THREAD

**Issue by mxa0079** [nx-dotnet/nx-dotnet#450]
**Is your feature request related to a problem? Please describe.**
Currently, the generator does not support creating a C# project for Azure Functions. Since Azure Functions support multiple languages and depends on a different cli to create its projects templates and is not included with the OOB dotnet templates.

**Describe the solution you'd like**
 I'd like to have nx dotnet generator OOB support for Azure Functions projects.

**Describe alternatives you've considered**
We can create a project folder, add the azure function project and wire it with nx manually. However, this requires lots of research for newcomers.

**Additional context**
Here is a link to create C# Azure Functions using the command line: https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-cli-csharp?tabs=azure-cli%2Cin-process

**Comment by AgentEnder** [comment]
Hey @mxa0079! This is something that would be interesting, that I hadn't originally considered for the scope of nx-dotnet.

If you use the functions cli to generate the project, can you run `nx g @nx-dotnet/core:import-projects` to generate the Nx configuration?

**Comment by mxa0079** [comment]
Ill give it a try

**Comment by mxa0079** [comment]
Hello @AgentEnder - Ive tried using import-projects w/o success. The documentation for the generator states:

[Projects inside the apps directory will include a serve target, while projects inside libs will only contain build + lint targets.](https://www.nx-dotnet.com/docs/core/generators/import-projects)

My apps are inside the packages folder. Could this be the issue?

**Comment by AgentEnder** [comment]
What is the actual error you are hitting? Is it just that there is no `serve` target?

**Comment by roldengarm** [comment]
Would be great to have native support for Azure Functions. It's annoying that an Azure Functions project cannot be created using `dotnet new` . 
I've gone for a Webjob project as that's just a console application, but that has less support, is not recommended anymore, and doesn't run on Linux App Services. 
Would be great to have support for Azure Functions project with NX Dotnet.

**Comment by AgentEnder** [comment]
@roldengarm As far as I can tell a functions project is just a c# project. Can you try generating them with the azure functions CLI and using the import-projects generator? @mxa0079 mentioned some issue but I'm not sure what it was.

**Comment by mxa0079** [comment]
Hello @AgentEnder -

I just tried to import it as a regular c# project and it first failed. I moved the new project to the app directory (instead of package) and the import command succeded. 

Is NX moving away from the packages folder structure and into an app folder structure?

So to summarize: I created the function project using de Azure Function CLI (func) and then I imported it using the `nx g @nx-dotnet/core:import-projects ` command and everything worked as expected.

**Comment by AgentEnder** [comment]
`import-projects` looks under the specified `apps` and `libs` directories from `nx.json`. If they are blank, (including in any preset that may be in the file), then it defaults to `apps` and `libs`.

**Comment by AgentEnder** [comment]
See: https://nx.dev/reference/nx-json#workspace-layout

**Comment by AgentEnder** [comment]
Nx isn't moving away from apps / libs, or away from the `packages` folder, they are each better for certain folks or preferences. You can even spec them as `.` and have the whole workspace be a bit less structured.

**Comment by cberthold** [comment]
I'm starting to look into this myself.  From what I can tell, having just gotten started in nx and nx-dotnet, a few days ago,  core:serve is just using dotnet run to execute.  Azure functions are bootstrapped by function core tools using func.exe. 

Output of what I get with the function app with a default function app using func.exe new and nx-dotnet webapi.

`
> nx run inventory-api:serve

Executing Command: dotnet "watch" "--project" "/mnt/c/code/research/critical-erp/apps/inventory-api/Critical.Erp.InventoryApi.csproj" "run" "--configuration" "Debug"
dotnet watch 🚀 Started
Unable to run your project.
Ensure you have a runnable project type and ensure 'dotnet run' supports this project.
A runnable project should target a runnable TFM (for instance, net5.0) and have OutputType 'Exe'.
The current OutputType is 'Library'.
dotnet watch ❌ Exited with error code 1
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...`

 I've put some output below for what we'd expect the serve target to do at a very high-level.  Passing project, etc. are options.  I'm looking into what executor to use to just run func and see if it works.
![image](https://user-images.githubusercontent.com/10100508/222721831-36813f24-ff77-41ea-8324-76159f8949cc.png)

**Comment by AgentEnder** [comment]
You can replace the whole target configuration with something like
```
{
  targets: {
    serve: {
      command: "func"
    }
  }
}
```

To try that out

**Comment by cberthold** [comment]
Success :)

Tried your suggestion first, I think it is pinned from workspace root.  func has to be run from project directory. 

Also tried this and it works.  "cwd" is the relative directory from workspace root.  I think with ports configured, I can figure out how to run envoy or Ocelot and have a pretty powerful microservice architecture with Micro-frontend tool-set.

What would be super useful for the nx:dotnet.  Support running func, func new to create new functions and changing environment variables just prior to running.  This is great though.  Thanks!

```
"serve": {
      "executor": "nx:run-commands",
      "options": {
        "commands": [
          "func start"
        ],
        "cwd": "apps/inventory-api",
        "parallel": false
      }
    },
    
   ```
   
   
![image](https://user-images.githubusercontent.com/10100508/222875779-406f28db-a0fc-4edf-aec5-7c886fe990b6.png)

**Comment by AgentEnder** [comment]
That error about the daemon could be a big deal, can you grab the contents of that error for me?

**Comment by AgentEnder** [comment]
I'm going to close this out. Generators + Executors for azure functions would be better suited for a new plugin.
