### ISSUE TITLE
[Feature] Generate Directory.Build.props during `init` generator

### ISSUE THREAD

**Issue by AgentEnder** [nx-dotnet/nx-dotnet#469]
## Current Behavior
Currently, we set the output path of C# projects in the monorepo individually. We do this by manually specifying them in each .csproj file. This has issues.
- If projects are moved, relative path is broken (see #406, #468)
- This is fragile, and a rather messy area of the codebase

## Desired Behavior
During `@nx-dotnet/core:init`, we should scaffold a minimal `Directory.Build.props` file that contains the setup for output paths.

**Additional context**
We need to ensure that the creation of this file is idempotent. `init` is called automatically at the beginning of each project generator, and the file shouldn't be recreated each time in case dev's customize it.

**Comment by tzuge** [comment]
I am currently setting up dotnet projects in a monorepo to better understand this. For 'app' vs 'lib', the output path is different in nx convention, and this appears to be achievable with dotnet by checking the SDK.

```xml
  <PropertyGroup Condition="'$(UsingMicrosoftNETSdkWeb)' == 'false'">
    <BaseOutputPath>$(RepoRoot)dist/libs/$(MSBuildProjectName)</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(UsingMicrosoftNETSdkWeb)' == 'true'">
    <BaseOutputPath>$(RepoRoot)dist/apps/$(MSBuildProjectName)</BaseOutputPath>
  </PropertyGroup>
```

**Comment by AgentEnder** [comment]
Thats insteresting too, but the workspace layout is determined by a property in `nx.json`. Ideally, we should read `nx.json` to determine the apps / libs folders when creating this file. `@nrwl/devkit` exports readWorkspaceConfiguration, which we can access the appsDir / libsDir with.

During `init`, we could use it to update these.

At the same time though, I'm not really a fan of checking for the .NET web SDK here... Console applications as an example would not be picked up. Nx traditionally classifies e2e as an app, which this would miss etc. Perhaps it would be better to not bother with libs/apps directory in the output path. Do something like: 

```json
  <PropertyGroup>
    <BaseOutputPath>$(RepoRoot)dist/nx-dotnet/$(MSBuildProjectName)</BaseOutputPath>
  </PropertyGroup>
```

**Comment by tzuge** [comment]
Agreed about using appsDir / libsDir from the workspace config during `init` creation of the Directory.Build.* files. Regarding excluding apps / libs from the output path, I feel like that's not ideal since it's different from the non-dotnet projects. 

Is there currently a generator that results in a project with `IsPackable` set to true? Although I suppose that really maps to "publishable libs" and not "libs"; perhaps should be the result in case of `nx g @nx-dotnet/core:classlib --publishable`.

**Comment by AgentEnder** [comment]
There is a different strategy to this that I've thought of that would match typical Nx dist output better. If we could represent `${workspaceRoot}/dist/${projectRoot}` in the Directory.Build.Props file than that would match up better than what we've been discussing.

There's not the concept of a publishable lib in nx-dotnet, the generators don't do a ton of extra stuff beyond `dotnet new` aside from 
- Setting up prebuild module boundaries task
- Setting up dist folder outputs

**Comment by tzuge** [comment]
Great idea. This seems to work.
```xml
<RepoRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RepoRoot>
<BaseOutputPath>$(RepoRoot)dist/$([System.IO.Path]::GetRelativePath($(RepoRoot), $(MSBuildProjectDirectory)))</BaseOutputPath>
```
