### ISSUE TITLE
[BUG] nx affected:test fails due to wrong node_modules location

### ISSUE THREAD

**Issue by georgechond94** [nx-dotnet/nx-dotnet#471]
**Describe the bug**
Everytime I run nx affected:test it fails with the following error:

```
EXEC : error : Cannot find module 'D:\source\repos\node_modules\@nx-dotnet\core\src\tasks\check-module-boundaries.js' [D:\source\repos\foo\libs\Com


D:\source\repos\foo\libs\Common\library\library.csproj(16,5): error MSB3073: The command "node ../../../../node_modules/@nx-dotnet/core/src/tasks


    ×  nx run tests:test
       Executing Command: dotnet "test" "D:\source\repos\foo\tests\tests\test.csproj"
Error: dotnet execution returned status code 1
    at DotNetClient.logAndExecute (D:\source\repos\foo\node_modules\.pnpm\@nx-dotnet+dotnet@1.12.0_kptnhmnqtji5wgbzvc6od2leri\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:159:19)
    at DotNetClient.test (D:\source\repos\foo\node_modules\.pnpm\@nx-dotnet+dotnet@1.12.0_kptnhmnqtji5wgbzvc6od2leri\node_modules\@nx-dotnet\dotnet\src\lib\core\dotnet.client.js:70:25)
    at D:\source\repos\foo\node_modules\.pnpm\@nx-dotnet+core@1.12.0_qf4sg3l462uolhxnmqtaod4ffa\node_modules\@nx-dotnet\core\src\executors\test\executor.js:17:41
    at Generator.next (<anonymous>)
    at fulfilled (D:\source\repos\foo\node_modules\.pnpm\tslib@2.4.0\node_modules\tslib\tslib.js:115:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 >  NX   Ran target test for 1 projects (57s)
```

What I noticed from the above is that it searches for a `node_modules` folder in the parent folder (D:\source\repos\node_modules) instead of my project's folder (D:\source\repos\foo\node_modules) where my `node_modules` folder lives.

I tried copying the `node_modules` folder from the project's folder to one folder above and everything worked as expected as the `D:\sources\repos\node_modules` existed.

Is there any setting that I might miss?

**To Reproduce**

**Expected behavior**

**Comment by AgentEnder** [comment]
In `D:\source\repos\foo\libs\Common\library\library.csproj` you should see a prebuild task that invokes node. You may need to remove a `../` from the path, its possible you moved the library at some point as this path doesn't get updated by the `@nrwl/workspace:move` generator.

See #406 and #470 for some discussion regarding this.

**Comment by georgechond94** [comment]
@AgentEnder that was exactly it. Strange that all my projects in this workspace had an extra `../`. Thanks!
