### ISSUE TITLE
[BUG] Can not create new projects in non english environments

### ISSUE THREAD

**Issue by mystiker** [nx-dotnet/nx-dotnet#480]
**Describe the bug**
It's impossible to run `nx g @nx-dotnet/core:app` in any non english (system?) environment out of the box. 

**To Reproduce**

1. ensure that the dotnet-cli does not output english localized text by running `dotnet new --list`
2. run `nx g @nx-dotnet/core:app`
3. follow up the wizard up to the point where you should choose a template
4. get the following error `Cannot read property '0' of undefined`

**Expected behavior**
I would expect the list of available templates in any given environment. However, this could be troublesome as the current implementation relies on localized strings from the dotnet-cli output.

**Environment:**

- dotnet@6.0.302
- @nx-dotnet/core@1.12.0

**Additional context**

The problem lies within the parsing of the output of the dotnet-cli. To get the option prompt with valid template options, the trail follows up to parseDotnetNewListOutput(rawOutput) in parse-dotnet-new-list-output.js:26. This function parses the output from `dotnet new --list` to get the available templates. But the parsing relies on having english column names and therefore, return undefined for (some) values per entity parsed from that table.

I don't know how the dotnet-cli gets the users language value and therefore, how to set it. But maybe one can launch a new shell with the english localization value to get around the parsing issues? Or just read the columns values index based?

**Workaround**
I ran into parse-dotnet-new-list-output.js:64 and added the matching strings from running `dotnet new --list`.

**Comment by AgentEnder** [comment]
This is fixed in https://github.com/nx-dotnet/nx-dotnet/commit/3c438e2236792c32a35d38a4429b3ebfdab12f13, but included in the commit by mistake. It won't show up in release notes as such, but should be fixed in next release.
