### ISSUE TITLE
[BUG]  swagger-typescript generator adds multiple identical import statements if more than one attribute has same ref type

### ISSUE THREAD

**Issue by Ossur** [nx-dotnet/nx-dotnet#498]
**Describe the bug**
When an object in the swagger.json file has two attributes with the same ref attribute, the generator adds two identical import statements, resulting in code that doesn't compile.

**To Reproduce**
1. Make a controller in a web api project return the following DTO
```csharp
public class WeatherForecast
{
    public int TemperatureC { get; set; }

    public string? Summary { get; set; }

    public Person Reporter { get; set; }
    
    public Person SoundEngineer { get; set; }
}

public class Person
{
    public string name { get; set; }
}
```
2. Build, then run the swagger generator and then the typescript swagger generator 
3. It should return this non-compiling typescript interface
```typescript
import { Person } from './person';
import { Person } from './person';

export interface WeatherForecast {
  temperatureC: number;
  summary?: string;
  reporter?: Person;
  soundEngineer?: Person;
}
```

**Expected behavior**
Only one import statement for Person should be generated

**Environment:**

- OS: Debian linux on WSL2

**Comment by Ossur** [comment]
Already found and fixed the bug, but don't know how to push it in

**Comment by aevartg** [comment]
+1 - need this fix

**Comment by AgentEnder** [comment]
Hey! Thanks for the report and recommended fix, I'm going to clean it up a tad bit and then push a PR containing it. 

As a side note, I had not been able to test the swagger typescript generator on more complex use cases. Have you all had any other issues?

**Comment by Ossur** [comment]
Thank you very much!

There are two issues we've run into: 

1. Frontend would like to have the possibility to have the `index.ts` file in a custom location, via options.
2. Date attributes are generated as strings, but should be generated as Date. A fix for that is here:
```
diff --git a/packages/core/src/generators/swagger-typescript/build-typescript-representation/parse-schema-object.ts b/packages/core/src/generators/swagger-typescript/build-typescript-representation/parse-schema-object.ts
index dfb4e17..9cca568 100644
--- a/packages/core/src/generators/swagger-typescript/build-typescript-representation/parse-schema-object.ts
+++ b/packages/core/src/generators/swagger-typescript/build-typescript-representation/parse-schema-object.ts
@@ -49,15 +49,27 @@ export function parsePropertyDefintion(
     typeof propertyDefinition.type === 'string' &&
     propertyDefinition.type in builtInTypeMap
   ) {
-    return {
-      type: builtInTypeMap[
-        propertyDefinition.type as keyof typeof builtInTypeMap
-      ],
-      nullable:
-        'nullable' in propertyDefinition
-          ? !!propertyDefinition.nullable
-          : false,
-    };
+    if (
+      propertyDefinition.format === 'date' ||
+      propertyDefinition.format === 'date-time'
+    ) {
+      return {
+        type: 'Date',
+        nullable:
+          'nullable' in propertyDefinition
+            ? !!propertyDefinition.nullable
+            : false,
+      };
+    } else
+      return {
+        type: builtInTypeMap[
+          propertyDefinition.type as keyof typeof builtInTypeMap
+        ],
+        nullable:
+          'nullable' in propertyDefinition
+            ? !!propertyDefinition.nullable
+            : false,
+      };
   } else if (propertyDefinition.type === 'object') {
     return {
       type: 'object',
diff --git a/packages/core/src/generators/swagger-typescript/constants/swagger-ts-type-map.ts b/packages/core/src/generators/swagger-typescript/constants/swagger-ts-type-map.ts
index 3a3afb8..c036396 100644
--- a/packages/core/src/generators/swagger-typescript/constants/swagger-ts-type-map.ts
+++ b/packages/core/src/generators/swagger-typescript/constants/swagger-ts-type-map.ts
@@ -3,6 +3,7 @@ export const builtInTypeMap = {
   integer: 'number',
   string: 'string',
   boolean: 'boolean',
+  date: 'Date',
 };
```

**Comment by AgentEnder** [comment]
@Ossur the choice to have Date / DateTime elements reflected as strings in the generated typescript was purposeful, as that is how the front end apps would receive the data unless you are doing some kind of special parsing. See https://stackoverflow.com/questions/69933406/proper-way-to-pass-date-objects-between-a-javascript-typescript-frontend-and-a-a

One company that I worked at patched JSON.parse to detect string properties which looked like a date and autoconvert them, but that's nonstandard so its not something that I'd want to type for by default. I'll do some thinking on this, perhaps we could make it an option.
