### ISSUE TITLE
[Feature] pass parameters from config to dotnet.exe params 

### ISSUE THREAD

**Issue by paul-hammant** [nx-dotnet/nx-dotnet#512]
**Is your feature request related to a problem? Please describe.**

My native dotnet.exe build needs custom parameters to be able to pass. Nx-dotnet doesn't have a provision for parameters.
These in particular:

```
dotnet build  /p:NetCoreBuild=true  /p:DacPacRootPath="C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE"  /p:NETCoreTargetsPath="$HOME\.nuget\packages\microsoft.build.sql\0.1.3-preview\tools\netstandard2.1"
```

**Describe the solution you'd like**

The ability to use `"options": {}` for specifying of `/p:` prefixed paramters without `--` being prepended before shelling out to dotnet.exe

**Describe alternatives you've considered**

I tried a number of placements of `extraParameters` and `dotnetBuildFlags` in experimental executions, but couldn't see them acted upon.

**Additional context**

## Hacky Solution

**New lines in file** `https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/dotnet/src/lib/core/dotnet.client.ts` (please forgive the JavaScript as my experiments were directly in node_modules for a project):

```
var params2 = [];
params.forEach(param => {
      params2.push(param.replace('--/p', '/p'));
 });
 params = params2; 
 // existing lines
 const cmd = `${this.cliCommand.command} "${params.join('" "')}"`;
 console.log(`Executing Command: ${cmd}`);
```

This allows this sort of thing to work in the pertinent project.json:

```
"build": {
  "executor": "@nx-dotnet/core:build",
  "outputs": ["dist/path/to/solution_project"],
  "options": {
    "configuration": "Debug",
    "noDependencies": true,
    "/p:NetCoreBuild=true": true,
    "/p:DacPacRootPath=\"C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\"": true,
    "/p:NETCoreTargetsPath=\"$HOME\\.nuget\\packages\\microsoft.build.sql\\0.1.3-preview\\tools\\netstandard2.1\"": true
  },
```

I was pleased to see the $HOME works in NodeJs config files on Windows :)

**Comment by paul-hammant** [comment]
OK the above is all wrong.  There's a use of `/p:` in the testbase already - https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/dotnet/src/lib/core/dotnet.client.spec.ts#L61

Where would that be specification in a real nx-dotnet build?  I can't map what I see in the test-code to production-code and configuration it would use.

**Comment by AgentEnder** [comment]
It looks like that functionality was added to the `publish` executor, but should probably be added to some of the other executors as well

**Comment by paul-hammant** [comment]
Yay!!  Great work @AgentEnder
