### ISSUE TITLE
[Feature] add back notional support for sqlproj

### ISSUE THREAD

**Issue by paul-hammant** [nx-dotnet/nx-dotnet#522]
**Is your feature request related to a problem? Please describe.**

A prior version was able to target .sqlproj projects within a .NET solution. Can we have it back, please?

**Describe the solution you'd like**

Change projPattern() in https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/utils/src/lib/utility-functions/glob.ts t also include .sqlproj

**Comment by paul-hammant** [comment]
Can confirm with the addition of |sql of this feature suggestion, #512 is fixed for us.

**Comment by AgentEnder** [comment]
Interesting that .sqlproj worked for you in the past, what do your targets look like for those projects? #19 has been a long standing issue that references better support for them, but I didn't think we had previously supported them in any real way.

Nonetheless, I'll cut a release with that updated pattern.

**Comment by paul-hammant** [comment]
Super responsive - thanks a bunch.

To your question - we have to add a bunch of /p: param to the dotnet.exe invocation.   Was all a PITA to setup - but the complexity was on the SSDT SDK additions that need to be overlaid on a .NET SDK install. The Nx side was easy by comparison.
