### ISSUE TITLE
[BUG] Getting started runs into Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Wowo10** [nx-dotnet/nx-dotnet#541]
**Describe the bug**
While trying to follow Getting started running into unexpected undefined. https://www.nx-dotnet.com/docs/core/

**To Reproduce**

1. Install empty nx project
`npx create-nx-workspace@latest package-based --preset=npm`
2. Install nx-dotnet/core
`npm i --save-dev @nx-dotnet/core`
3. Init nx-dotnet
`npx nx g @nx-dotnet/core:init`
4. Generate your first api
`npx nx g @nx-dotnet/core:app my-api --test-template nunit --language C#`
5. Choose any template nx/dotnet
6. See the error

**Expected behavior**
Created example .Net Api

**Log --verbose**
>  NX  Generating @nx-dotnet/core:application

√ Which path naming conventions should the project use? · dotnet

 >  NX   Cannot read properties of undefined (reading '0')

TypeError: Cannot read properties of undefined (reading '0')
    at C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\@nx-dotnet\core\src\generators\utils\prompt-for-template.js:19:36
    at Array.map (<anonymous>)
    at promptForTemplate (C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\@nx-dotnet\core\src\generators\utils\prompt-for-template.js:18:32)
    at C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\@nx-dotnet\core\src\generators\utils\generate-project.js:56:74
    at Generator.next (<anonymous>)
    at C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\tslib\tslib.js:114:16)
    at getTemplate (C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\@nx-dotnet\core\src\generators\utils\generate-project.js:53:20)
    at C:\Wowos\Projects\nx\dotnet-my-ass\node_modules\@nx-dotnet\core\src\generators\utils\generate-project.js:27:32

**Environment:**

- OS: Windows 10
- .Net Core SDK --version : 3.1.423
- npm --version : 8.15.0
- node --version : 16.17.1

**Comment by AgentEnder** [comment]
Can you provide the output from `dotnet new --list`? We use that output to prompt for available templates and it appears to be failing in your case.

**Comment by Wowo10** [comment]
After installing .Net 6 isntead 3.1 it works.

**Comment by AgentEnder** [comment]
Ideally it should work on 3.1,  but we can close this out if it's working for you now.
