### ISSUE TITLE
CheckNxModuleBoundaries target fails on project root with a space in it

### ISSUE THREAD

**Issue by remkoboschker** [nx-dotnet/nx-dotnet#550]
**Describe the bug**
building a project with a space in the project root path fails because when a `--project-root` argument is passed to `check-module-boundaries.js` with a space the `process.argv` array has only the first part of the path.  See https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/core/src/tasks/check-module-boundaries.ts#L91

**To Reproduce**

1. make a project with a space in the path
2. call npx nx run project:build

**Expected behavior**

The task runs without problems

**Screenshots**

**Environment:**

nx 15.0.0
@nx-dotnet/core: 1.15.0
windows 11
node 16.17.1

**Comment by remkoboschker** [comment]
I made a pr that avoids the issue https://github.com/nx-dotnet/nx-dotnet/pull/551 not sure if it should not be handled in check-modules-boundaries.js as well.

**Comment by AgentEnder** [comment]
I think this should be fixed by #551, I'm going to go ahead and close this out.
