### ISSUE TITLE
add methods for each end point in swagger-typescript generator

### ISSUE THREAD

**Issue by remkoboschker** [nx-dotnet/nx-dotnet#554]
**Is your feature request related to a problem? Please describe.**
To maximise the utility of open api documentation and avoid the need for looking up the endpoint paths and parameters it would be nice to generate methods that call a specific end point using a particular http method.

**Describe the solution you'd like**
* method for each endpoint / http method
* config for auth
* allow wrapper for custom error handling

**Describe alternatives you've considered**
There are several options the generate clients, but it would be nice to include in the nx plugin. For instance https://github.com/acacode/swagger-typescript-api, https://github.com/hosseinmd/swagger-typescript or https://github.com/cyclosproject/ng-openapi-gen

**Additional context**

**Comment by AgentEnder** [comment]
Hey @remkoboschker! Generating clients, methods, or similar is outside the scope of the plugin. If you wish to go further down the codegen side of things, there is an existing Nx plugin that I'd recommend: https://www.npmjs.com/package/@trumbitta/nx-plugin-openapi

Using it, you should be able to just swap out the codegen target for one using its executors. The philosophy behind how we set up codegen lines up very nicely with theirs.

**Comment by remkoboschker** [comment]
Great, thank you
