### ISSUE TITLE
[BUG] .NET lint executed without such target

### ISSUE THREAD

**Issue by dstoyanoff** [nx-dotnet/nx-dotnet#566]
**Describe the bug**
Hello,
I have a strange problem with a nx workspace with both frontend apps and .NET apps. Previously, I used to have a lint target for all that would use eslint for the frontend projects and format for the .NET apps. I have not deleted the lint target from the project.json files for all projects, but running lint still executes dotnet format and I can't understand why. Removing the plugin from nx.json and running lint throws "Cannot find configuration for task <project>:lint", but when I bring it back, it executes the lint again. How do I stop it?

**Environment:**
Report complete - copy this into the issue template

   Node : 16.13.2
   OS   : darwin arm64
   yarn : 1.22.15
   
   nx : 15.0.13
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.0.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.13
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.13
   @nrwl/js : 15.0.13
   @nrwl/linter : 15.0.13
   @nrwl/nest : Not Found
   @nrwl/next : 15.0.13
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.0.13
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.13
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.13
   @nrwl/web : 15.0.13
   @nrwl/webpack : 15.0.13
   @nrwl/workspace : 15.0.13
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nx-dotnet/core: 1.16.0

**Comment by AgentEnder** [comment]
There's a flag in .nxdotnetrc.json to disable the inference behavior... Here: https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/utils/src/lib/models/nx-dotnet-config.interface.ts#L25
