### ISSUE TITLE
Moving from deprecated workspace.json to project.json does not work (?)

### ISSUE THREAD

**Issue by janzwanenburg** [nx-dotnet/nx-dotnet#570]
**Describe the bug**
I have created a sample nx-dotnet workspace with 3 .NET projects, which works fine.
(Based on the Nx dotnet After Dark tutorial video.)
This includes a workspace.json file. I have seen the workspace.json approach is deprecated, see 
https://nx.dev/deprecated/workspace-json.
I wanted to move to a project.json approach, so I followed the instructions to do so, but the result does not build at all anymore.

**To Reproduce**
* Have a working nx dotnet set-up, e.g. as explained above.
* Modify the version in workspace.json to 2
* Run the command given by the nx instructuons
```
nx g @nrwl/workspace:convert-to-nx-project --all
```
* That seems to work fine, I have now a much shorter workspace.json, and individual project.json files next to my csproj files.
* When I try to build using nx build weatherApi, I get response
```
 >  NX

   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```
with a red box around 'NX'. 
* nx reset does not help.

**Expected behavior**
I expected the nx build command to work as before.

**Screenshots**
None.

**Environment:**

- OS: Windows 10
- Browser: N.A.
- Version: nx version 15.2.1

**Additional context**
Wondering whether project.json is supported at all for nx dotnet.

**Comment by AgentEnder** [comment]
That should be a supported workflow. You can see in this repo a working example, of you look at the configuration. 

Can you run the command with NX_VERBOSE_LOGGING=true and NX_DAEMON=false? That should provide a better stack trace.

Also, what's nx report say?

**Comment by janzwanenburg** [comment]
Thanks @AgentEnder.
It's good to know that this workflow is supported, since we want to use it for a monorepo with ~600 csproj projects.
Having all configured centrally would be very awkward.

I have set the flags as suggested. That gives the following response:
```
C:\views\experiment-nx-dotnet-monorepo>nx build weather-api
Skipping project inferred from AIP\NetFrameworkApp\NetFrameworkApp\NetFrameworkApp.csproj since project netframeworkapp already exists.

 >  NX


Error
    at buildWorkspaceConfigurationFromGlobs (C:\views\experiment-nx-dotnet-monorepo\node_modules\nx\src\config\workspaces.js:642:27)
    at Workspaces.readWorkspaceConfiguration (C:\views\experiment-nx-dotnet-monorepo\node_modules\nx\src\config\workspaces.js:57:27)
    at readAllWorkspaceConfiguration (C:\views\experiment-nx-dotnet-monorepo\node_modules\nx\src\config\configuration.js:15:72)
    at C:\views\experiment-nx-dotnet-monorepo\node_modules\nx\src\project-graph\build-project-graph.js:25:89
    at Generator.next (<anonymous>)
    at C:\views\experiment-nx-dotnet-monorepo\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\views\experiment-nx-dotnet-monorepo\node_modules\tslib\tslib.js:114:16)
    at buildProjectGraph (C:\views\experiment-nx-dotnet-monorepo\node_modules\nx\src\project-graph\build-project-graph.js:24:20)
    at C:\views\experiment-nx-dotnet-monorepo\node_modules\nx\src\project-graph\project-graph.js:66:66
```

Probably it is something silly from my end, but I find it hard to get a lead from this stack trace.

**Comment by AgentEnder** [comment]
Thanks. What's nx report output? Also, you may be able to add some logs around the lines in the stack trace to figure out which project is giving issues.

**Comment by bcallaghan-et** [comment]
@janzwanenburg Are any of your .NET projects using .NET Framework, as opposed to .NET Core or .NET 5+? In my own experience, the project.json style of configuration works with .NET Core and .NET 5+, but it does not work with .NET Framework. There was a brief time in .NET's own history that it used project.json files, instead of the standard .csproj files. I've found that if a traditional .NET Framework project has both a .csproj and a project.json, the .NET CLI favors the project.json, which (since it's actually an Nx file) fails on every command. Since my workspace has a mix of .NET Framework and .NET 5+ (hoping to remove the Framework parts anyway), I use project.json for most projects, and I keep the .NET Framework project configuration in workspace.json.

**Comment by janzwanenburg** [comment]
@bcallaghan-et , Thanks for hitting the nail on the head!

Yes, one of my .NET projects was using the .NET Framework. Deleting that project works around the issue.
For my sample workspace, I can successfully run Nx with the project.json files for .NET Core / .NET 5+.

However, for our proper production repo, we have ~300 .NET Framework projects, so this is a bit of a bummer.
It will probably take a few years before we have migrated those to .NET 5+.
One option is to keep .NET Fwk projects in the central workspace.json, but with 300 projects that is awkward.

Do you happen to have any suggestions/experience on how to work with project.json files for .NET Frameworks?
I will also pursue this with .NET experts.

**Comment by bcallaghan-et** [comment]
@janzwanenburg My general suggestion would be to upgrade those projects to .NET 6, but I recognize that will take significant time and effort. Another possibility (which I haven't tested myself) is to convert the .NET Framework projects to SDK-style projects, while still targeting .NET Framework. The CLI should then favor the .csproj and ignore the project.json file.

**Comment by janzwanenburg** [comment]
Update from my side.
I found two possible solutions:
* Convert csproj to sdk style (this is possible while keeping .NET Framework as target)
* Add MyProjectName.project.json file next to the csproj file. MSBuild will prefer this file over the project.json meant for nx, so the name clash is avoided. Sample contents of this new file for MsBuild that works in our setup:
```
{
  "runtimes": { "win": { } },
  "frameworks": { "net472": { } }
}
```
For me the issue and reasonable workarounds are clear, so closing the issue.
