### ISSUE TITLE
[BUG] Getting issue while building the project

### ISSUE THREAD

**Issue by amitkpal83** [nx-dotnet/nx-dotnet#578]
Hi,

I have added the nx-workspace and then add few projects in the workspace. But when i am trying to build the project it is not getting build. Please see the below screenshots.

![image](https://user-images.githubusercontent.com/6175985/207885654-5b6fa562-004f-45a4-9f75-a76f76b796b3.png)

![image](https://user-images.githubusercontent.com/6175985/207885870-1798f40f-6303-4588-b54a-e0334b3d7a0a.png)

Also i need help. Gone through the documentation but not getting instructions. I am having existing project with lot of libraries and web application. How i will port this project to nx-workspace with solution file. And then need to build project through solution file. To be precise where i have to copy the full project. Have tried and then executed the import command but that is not working and workspace not able to identify the project. 

Please help. Do let me know if you need more information.

- Windows
- chrome
- 15

**Comment by AgentEnder** [comment]
What files are under packages/my-app?

**Comment by amitkpal83** [comment]
I have attached the code. Please do answer for other questions also asked above.
[my-app.zip](https://github.com/nx-dotnet/nx-dotnet/files/10243099/my-app.zip)

**Comment by amitkpal83** [comment]
@AgentEnder Also when i am generating the workspace. Apps and libs folder not generating. Anything wrong i am doing?

**Comment by amitkpal83** [comment]
@AgentEnder Please help

**Comment by AgentEnder** [comment]
I think the error is because the csproj file starts with a `.`. The glob probably doesn't see it since its "hidden".

Regarding apps / libs folder not generating, that just depends on the workspace preset you pick when doing `npx create-nx-workspace`, if you use the `apps` preset as an example you'd still get them.
