### ISSUE TITLE
[BUG] Import project command is not working

### ISSUE THREAD

**Issue by amitkpal83** [nx-dotnet/nx-dotnet#582]
Hi,
I have created a workspace and imported few projects. But when i run the command "nx g @nx-dotnet/core:import-projects nothing gets imported. It is giving below output after running the command:
"Generating @nx-dotnet/core:import-projects"

But after that nothing it will show.

Attaching a zip file of whole project where i have moved few projects in lib and app folder. Removed node_modules folder due to size. When i try to build one of these project it will say  Cannot find project 'Library2' after running the import command.
[Code.zip](https://github.com/nx-dotnet/nx-dotnet/files/10276470/Code.zip)

- OS: [e.g. iOS] - windows

**Comment by AgentEnder** [comment]
Your `nx.json` file extends "nx/presets/npm.json", which specifies appsDir & libsDir as `packages`. The `import-projects` generator only looks under those 2 directories (or in this case, the 1 directory).

See: https://nx.dev/reference/nx-json#workspace-layout

**Comment by amitkpal83** [comment]
Hi @AgentEnder Thanks for helping. Still when i have moved library to libsDir folder and executed import command getting below error.
![image](https://user-images.githubusercontent.com/6175985/209112450-c5908085-7727-4219-9ce0-25c41c645a69.png)

Tried with new empty workspace also but still same. Done the nx reset also multiple times but no luck

**Comment by amitkpal83** [comment]
![image](https://user-images.githubusercontent.com/6175985/209112957-90ab00b0-cb2d-4ac7-9731-3f085dbc2433.png)
This is with stacktrace

**Comment by amitkpal83** [comment]
@AgentEnder Pls help. I am having project with huge number of libraries which i need to setup. But not able to proceed with simple import project only. May be it is silly mistake from my end only. Have gone through the documentation but not able to resolve this.

**Comment by AgentEnder** [comment]
@amitkpal83 what is not working for you? The stack trace provided earlier should be resolved in latest.

**Comment by amitkpal83** [comment]
@AgentEnder Yup that dot issue is resolved and build is working fine. Above stacktrace is coming when i trying to run the import project command. I am just copying one library to libsDir folder and trying to import but it is not getting imported. Above i have attached the zip file of code and stacktrace also.

**Comment by amitkpal83** [comment]
@AgentEnder I know its holiday time. But by any chance did you see my message above.
