### ISSUE TITLE
[Question] swagger codegen not working in generated lib when `useNxPluginOpenAPI:true`

### ISSUE THREAD

**Issue by Tungsten78** [nx-dotnet/nx-dotnet#598]
Relates to #589.

I'm having issues with `nx codegen [generated-swagger-lib]` created via `nx g [app] useNxPluginOpenAPI:true`
* [`@trumbitta/nx-plugin-openapi` executes `npx openapi-generator-cli`](https://github.com/trumbitta/nx-trumbitta/blob/85f210ff9b1a3e1f6a7b34194724e8b0ebf268da/packages/nx-plugin-openapi/src/executors/generate-api-lib-sources/executor.ts#L54) which errors because it's missing the scope (@openapitools/openapi-generator-cli)

Is npx capable of resolving this without the [scope](https://www.npmjs.com/package/@openapitools/openapi-generator-cli) for you @AgentEnder?

**Comment by Tungsten78** [comment]
Potential clue:   `npx` looks to resolve it if the package is already installed globally

**Comment by AgentEnder** [comment]
Can you try running yarn or npm I and then retracing the command? We may not be running the necessary install after generation.

**Comment by Tungsten78** [comment]
Yes, this solves the issue.  

On closer inspection `@openapitools/openapi-generator-cli` was added to to workspace's package.json by `@trumbitta/nx-plugin-openapi`.

Which of the two plugins doing generation here is responsible to install?  or is this expected to be a manual step?

**Comment by Tungsten78** [comment]
perhaps related, immediately after generating the webapi app itself:
* the build dependency works, but any other target produces a similar result (serve/lint/etc)
```
C:\Users\CML0906\Source\nx-trends>nx swagger test-api   

> nx run test-api:build  [existing outputs match the cache, left as is]

Executing Command: dotnet "--version"
7.0.102
Executing Command: dotnet "build" "C:\Users\CML0906\Source\nx-trends\apps\test-api\NxTrends.TestApi.csproj" "--configuration" "Debug" "--no-dependencies" "--verbosity" "minimal"
MSBuild version 17.4.1+9a89d02ff for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  NxTrends.TestApi -> C:\Users\CML0906\Source\nx-trends\dist\apps\test-api\net7.0\NxTrends.TestApi.dll
  Checking module boundaries for test-api

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.03

> nx run test-api:swagger

 >  NX   Could not find project "test-api"
   Pass --verbose to see the stacktrace.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target swagger for project test-api and 1 task(s) they depend on (693ms)

    ×    1/2 failed
    √    1/2 succeeded [1 read from cache]

**Comment by Tungsten78** [comment]
Scratch the observation about `nx build test-api` working despite `nx swagger test-api` not.   The nx-cache is at play here.

**Comment by AgentEnder** [comment]
We should be running an install task, I'll double check why its not getting hit.
