### ISSUE TITLE
[BUG] Nx Console Generate UI does not work with nx-dotnet generators

### ISSUE THREAD

**Issue by ntziolis** [nx-dotnet/nx-dotnet#64]
**Describe the bug**
When using the Nx Console UI the the nx-dotnet generators do show up in the list. But when selecting either of them nothing happens. No options are shown and the generator is not executed.

**To Reproduce**
- Ensure Nx Console extension is installed
- Use Nx Console to generate
- Select @nx-dotnet/core app

**Expected behavior**
After selecting the generator a page with all options of a given generator should show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/265338/121126397-62658700-c828-11eb-9c9e-4aedb7392262.png)

**Environment:**
- OS: WSL (Ubuntu 20.04)
- Package (latest)

**Comment by AgentEnder** [comment]
This issue is related to nrwl/nx-console#1080

**Comment by ntziolis** [comment]
@AgentEnder Yes I can now confirm that its an issue with nx console as when reverting back to `17.3.1` of the console the options page is properly shown.

**Comment by AgentEnder** [comment]
Ok, great 👍.  I'll close this out, as it should be fixed whenever nx-console is updated.
