### ISSUE TITLE
[BUG] CI NX Cached referenced dotnet projects will result in a failed build project of non-cached project - try 2

### ISSUE THREAD

**Issue by mxa0079** [nx-dotnet/nx-dotnet#656]
### Current Behavior

When trying to build a project which uses another project, cached by NX, will result in a build failure for not finding the DLL.

If I add the flag --skip-nx-cache the build completes successfully.

If I remove this flag the build fails with the following log:

```
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
  Determining projects to restore...
  Restored /Users/runner/work/1/s/libs/quote-kernel/Comodin.Shared.QuoteKernel.csproj (in 167 ms).
  Restored /Users/runner/work/1/s/libs/qualitas/Comodin.Qualitas.csproj (in 1.26 sec).
  Restored /Users/runner/work/1/s/libs/seguros-ana/Comodin.SegurosAna.csproj (in 2.84 sec).
  Restored /Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj (in 2.84 sec).
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/qualitas/obj/Release/net6.0/ref/Comodin.Qualitas.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/seguros-ana/obj/Release/net6.0/ref/Comodin.SegurosAna.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/quote-kernel/obj/Release/net6.0/ref/Comodin.Shared.QuoteKernel.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]

Build FAILED.

CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/qualitas/obj/Release/net6.0/ref/Comodin.Qualitas.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/seguros-ana/obj/Release/net6.0/ref/Comodin.SegurosAna.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/quote-kernel/obj/Release/net6.0/ref/Comodin.Shared.QuoteKernel.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
    0 Warning(s)
    3 Error(s)
```

### Expected Behavior

The build should succeed using the nx cache.

### Steps to Reproduce

1. Create a project (ie: 'ReferenceProject') with a class which will be called in the project B
2. Run a CI build with ReferenceProject, making it cached
3. Create a second project (ie: 'CallingProject'), reference it to 'ReferenceProject'
4. Run this on the CI (Azure DevOps)
5. the CI build will fail:

### Nx Report

```shell
Node : 18.14.2
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.3.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.3
   @nrwl/js : 15.3.3
   @nrwl/linter : 15.3.3
   @nrwl/nest : Not Found
   @nrwl/next : 15.3.3
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.3
   @nrwl/web : 15.3.3
   @nrwl/webpack : 15.3.3
   @nrwl/workspace : 15.3.3
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nx-dotnet/core: 1.16.2
```

### nx.json

```json
{
  "extends": "nx/presets/core.json",
  "npmScope": "comodin",
  "affected": {
    "defaultBase": "main"
  },
  "cli": {
    "defaultCollection": "@nrwl/next"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "@nrwl/nx-cloud",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e"
        ],
        "accessToken": "XXXX="
      }
    }
  },
  "plugins": [
    "@nx-dotnet/core"
  ],
  "generators": {
    "@nrwl/react": {
      "application": {
        "babel": true
      }
    },
    "@nrwl/next": {
      "application": {
        "style": "css",
        "linter": "eslint"
      }
    }
  },
  "defaultProject": "comodin-web-app",
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "inputs": [
        "production",
        "^production"
      ]
    },
    "e2e": {
      "inputs": [
        "default",
        "^production"
      ]
    },
    "test": {
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/jest.preset.js"
      ]
    },
    "lint": {
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json"
      ]
    },
    "build-storybook": {
      "inputs": [
        "default",
        "^production",
        "{workspaceRoot}/.storybook/**/*"
      ]
    },
    "postbuild": {
      "dependsOn": [
        "^postbuild"
      ],
      "inputs": [
        "default",
        "^production"
      ]
    }
  },
  "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
  },
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "sharedGlobals": [
      "{workspaceRoot}/babel.config.json"
    ],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/jest.config.[jt]s",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/.storybook/**/*",
      "!{projectRoot}/**/*.stories.@(js|jsx|ts|tsx|mdx)"
    ]
  }
}
```

### Failure Logs

```shell
Executed command:

nx run-many --target=build --projects=quote-kernel,seguros-ana,qualitas,catalog,comodin-api,comodin-catalog-api,comodin-catalog-serverless,shared-ui --configuration=production

Full logs:

Executing Command: dotnet "--version"
7.0.201
Executing Command: dotnet "build" "/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj" "--configuration" "Release" "--no-dependencies" "--verbosity" "minimal"

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.201

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
MSBuild version 17.5.0-preview-23061-01+040e2a90e for .NET
  Determining projects to restore...
  Restored /Users/runner/work/1/s/libs/quote-kernel/Comodin.Shared.QuoteKernel.csproj (in 167 ms).
  Restored /Users/runner/work/1/s/libs/qualitas/Comodin.Qualitas.csproj (in 1.26 sec).
  Restored /Users/runner/work/1/s/libs/seguros-ana/Comodin.SegurosAna.csproj (in 2.84 sec).
  Restored /Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj (in 2.84 sec).
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/qualitas/obj/Release/net6.0/ref/Comodin.Qualitas.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/seguros-ana/obj/Release/net6.0/ref/Comodin.SegurosAna.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/quote-kernel/obj/Release/net6.0/ref/Comodin.Shared.QuoteKernel.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]

Build FAILED.

CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/qualitas/obj/Release/net6.0/ref/Comodin.Qualitas.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/seguros-ana/obj/Release/net6.0/ref/Comodin.SegurosAna.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/quote-kernel/obj/Release/net6.0/ref/Comodin.Shared.QuoteKernel.dll' could not be found [/Users/runner/work/1/s/libs/catalog/Comodin.Catalog.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:09.28

 >  NX   dotnet execution returned status code 1
```

### Additional Information

NX Cloud reports this as a cache miss

**Comment by AgentEnder** [comment]
This is the PR that includes the fix: https://github.com/nx-dotnet/nx-dotnet/pull/596

Notably, it was added in 1.18.1, after your current version. The key thing here is just that your `outputs` property for the build targets needs to include the path to the `obj` folder.

After 1.18.1, we redirect them into dist but that is truly optional. The big thing is just making sure Nx knows to restore that folder.

**Comment by mxa0079** [comment]
Thanks @AgentEnder - I suggest updating the original issue #489 with this information.

https://github.com/nx-dotnet/nx-dotnet/issues/489

**Comment by mxa0079** [comment]
Hello @AgentEnder  -

I hope you are doing well.

We have updated to the latest NX and the latest dotnet-nx plugin versions. This has helped. However, the issue STILL happens, but now it is intermittently.

If something is wrong with our paths, Id rather have it failing consistently (regardless of the environment) instead of intermittently or environment depending.

Could you please expand upon your comment: "The key thing here is just that your outputs property for the build targets needs to include the path to the obj folder."

Thanks,

Mau

**Comment by mxa0079** [comment]
Hello,

How can we re-open this issue? What proof do you need that it is still happening in the latest version?

**Comment by mxa0079** [comment]
Here are the logs of the issue persisting. This same build works correctly on my local machine, but it intermittently fails in the CI:



  Restored /Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj (in 3.64 sec).
/Users/runner/.dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(54,5): warning RAZORSDK1007: Reference assembly /Users/runner/work/1/s/dist/packages/seguros-ana/net6.0/Comodin.SegurosAna.dll could not be found. This is typically caused by build errors in referenced projects. [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/catalog/obj/Release/net6.0/ref/Comodin.Catalog.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/qualitas/obj/Release/net6.0/ref/Comodin.Qualitas.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/seguros-ana/obj/Release/net6.0/ref/Comodin.SegurosAna.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/quote-kernel/obj/Release/net6.0/ref/Comodin.Shared.QuoteKernel.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]

Build FAILED.

/Users/runner/.dotnet/sdk/7.0.202/Sdks/Microsoft.NET.Sdk.Razor/targets/Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets(54,5): warning RAZORSDK1007: Reference assembly /Users/runner/work/1/s/dist/packages/seguros-ana/net6.0/Comodin.SegurosAna.dll could not be found. This is typically caused by build errors in referenced projects. [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/catalog/obj/Release/net6.0/ref/Comodin.Catalog.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/qualitas/obj/Release/net6.0/ref/Comodin.Qualitas.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/seguros-ana/obj/Release/net6.0/ref/Comodin.SegurosAna.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
CSC : error CS0006: Metadata file '/Users/runner/work/1/s/libs/quote-kernel/obj/Release/net6.0/ref/Comodin.Shared.QuoteKernel.dll' could not be found [/Users/runner/work/1/s/packages/comodin-catalog-api/Comodin.ComodinCatalogApi.csproj]
    1 Warning(s)
    4 Error(s)

Time Elapsed 00:00:12.35

 >  NX   dotnet execution returned status code 1

   Pass --verbose to see the stacktrace.


 

 >  NX   Running target build for 7 projects failed

   Failed tasks:
   
   - comodin-catalog-api:build:production

   View structured, searchable error logs at https://cloud.nx.app/runs/IYGAzdfHFe

##[debug]Exit code 1 received from tool '/bin/bash'
##[debug]STDIO streams have closed for tool '/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]
Finishing: NX Build Server Components
