### ISSUE TITLE
[BUG] Weird error when building docker image

### ISSUE THREAD

**Issue by illunix** [nx-dotnet/nx-dotnet#725]
### Current Behavior

I get this error when i try to build my docker image, normal builds work

### Expected Behavior

Should build image

### Steps to Reproduce

1.
![image](https://github.com/nx-dotnet/nx-dotnet/assets/42069493/5324c7b6-cee6-4b1f-92dc-c75cd316f812)

### Nx Report

```shell
...
```

### nx.json

```json
...
```

**Comment by AgentEnder** [comment]
You'll need to copy node_modules/@nx-dotnet/core into your node_modules, or remove the boundaries check from your build process.

**Comment by syazell1** [comment]
> You'll need to copy node_modules/@nx-dotnet/core into your node_modules, or remove the boundaries check from your build process.

Thank you! it works on my end now.

I chose the latter approach, and it works, by removing this tag.
```
  <Target Name="CheckNxModuleBoundaries" BeforeTargets="Build">
    <Exec Command="node $(NodeModulesRelativePath)/node_modules/@nx-dotnet/core/src/tasks/check-module-boundaries.js --project-root &quot;$(MSBuildProjectDirRelativePath)&quot;"/>
  </Target>
```
