### ISSUE TITLE
[BUG] Unexpected dependency from dotnet libraries to other project in monorepo

### ISSUE THREAD

**Issue by JakeDern** [nx-dotnet/nx-dotnet#743]
### Current Behavior

I have a monorepo structured roughly like this:
```
example/
├── nx.json
├── package.json
├── project.json <- "Project A"
└── projects
    ├── dotnet-app
    │   ├── dotnet-app.sln
    │   ├── README.md
    │   └── src
    │       ├── lib1
    │       │   ├── lib1.csproj
    │       │   └── project.json
    │       ├── lib2
    │       │   ├── lib2.csproj
    │       │   └── project.json
    │       └── lib3
    │           ├── lib3.csproj
    │           └── project.json
    └── otherproject
        └── project.json
```

In this repo lib1 and lib2 depend on lib3. The nx-dotnet plugin is correctly modeling these dependencies, but it is also listing "Project A" as a dependency of lib1 and lib2. This is verified via nx graph file output and running commands. It does not do this for lib3.

This behavior goes away when I uninstall the plugin, but then I have to model dependencies myself and in the real project I have 10 libs instead of the three here. I would rather delegate that to the plugin if possible.

I am happy to get my hands dirty if you can direct me on how to debug this issue. I'll report back with anything that I find, but I'm not fully sure where to start.

### Expected Behavior

No dependency from the dotnet libraries to "Project A"

### Steps to Reproduce

Apologies, I have not been able to set up a full repro. If necessary I can attempt it, but I cannot publish the original repo.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.14.0
   OS     : linux-x64
   npm    : 9.7.2
   
   nx             : 16.5.0
   @nx/workspace  : 16.5.0
   @nx/devkit     : 16.5.0
   @nrwl/tao      : 16.5.0
   typescript     : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core        : 1.22.0
   @nx-tools/nx-container : 5.0.2
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "plugins": [
    "@nx-dotnet/core",
    "@nx-tools/nx-container"
  ],
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "test",
          "image",
          "generate",
          "lint",
          "verify",
          "publish"
        ]
      }
    }
  },
  "namedInputs": {
  },
  "targetDefaults": {
    "image": {
      "dependsOn": [
        "build"
      ],
      "options": {
        "engine": "docker",
        "load": false,
        "cache-to": [
          "type=inline"
        ]
      },
      "defaultConfiguration": "dev",
      "configurations": {
        "dev": {
          "outputs": [
            "type=docker"
          ]
        },
        "tar": {
          "outputs": [
            "type=tar"
          ]
        }
      }
    },
    "lint": {
      "configurations": {
        "ci": {}
      }
    },
    "build": {
      "dependsOn": [
        "^build"
      ]
    }
  },
  "installation": {
    "version": "16.5.0"
  }
}
```

**Comment by AgentEnder** [comment]
Hey @JakeDern - this is a good find. Nx didn't support nested projects when we started the plugin. #763 changes over the dependency detection + file -> project resolution to something closer to what we use in the main Nx repo, so it should be more consistent.
