### ISSUE TITLE
[BUG]  Used vulnerable package (semver)

### ISSUE THREAD

**Issue by tidusjar** [nx-dotnet/nx-dotnet#751]
### Current Behavior

Currently the semver package being used (7.3.9) has a ReDoS vulnerability that has been fixed in a later minor version: https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795

### Expected Behavior

Upgrade package to reduce vulnerable libraries

### Steps to Reproduce

N/A

### Nx Report

```shell
N/A
```

### nx.json

```json
N/A
```

### Failure Logs

```shell
N/A
```

**Comment by AgentEnder** [comment]
nx-dotnet is a development dependency, so this kind of regex attack isn't viable. We will likely upgrade it at the same time as Nx, so its coming soon, but I'm going to close this out as its not relevant for the project.
