### ISSUE TITLE
[Feature] Missing step in Onboarding docs

### ISSUE THREAD

**Issue by Siphonophora** [nx-dotnet/nx-dotnet#760]
**Is your feature request related to a problem? Please describe.**
Following steps through https://www.nx-dotnet.com/docs/core#generate-and-run-your-first-api works fine. But if you then try to run test, on a clean workspace, you will find that run-many build tries to build both the api and test projects in parallel. The test project then fails if the api project hasn't built before.

**Describe the solution you'd like**
Add additional steps. For me everything worked once I added the following.

``` json
// nx.json
  "targetDefaults": {
    "build": {
      "dependsOn": [
        "^build"
      ]
    }
  },
```

**Comment by AgentEnder** [comment]
Hey @Siphonophora 👋 - you mentioned this being a clean workspace. **_Most_** nx workspaces default to having build depend on build like that, including newly created ones (see: https://github.com/nrwl/nx/blob/master/packages/workspace/src/generators/new/generate-workspace-files.ts#L82-L86)

How did you create the workspace in question?

**Comment by Siphonophora** [comment]
I haven’t used nx before so I didn’t have a workspace before.

Not in a position to repo right now. But I
think I just followed the steps on your guide, using the npm option.

**Comment by AgentEnder** [comment]
This should be fixed up now
