### ISSUE TITLE
[Feature] Add support for `allSourceTags` in enforce module boundaries implementation

### ISSUE THREAD

**Issue by Tungsten78** [nx-dotnet/nx-dotnet#768]
From [documentation](https://nx.dev/nx-api/eslint-plugin/documents/enforce-module-boundaries#dependency-constraints), more complex rules were written to find out they weren't working.  
* nx-dotnet has its own implementation (see [check-module-boundaries.js](https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/core/src/tasks/check-module-boundaries.ts)).

**Comment by AgentEnder** [comment]
Closed by #771
