### ISSUE TITLE
[BUG] Format boolean command line options don't work with false

### ISSUE THREAD

**Issue by flippidippi** [nx-dotnet/nx-dotnet#797]
### Current Behavior

When running linting, by default, we get the correct command to lint and not "fix":
`dotnet "format" "hello/Hello.csproj" "--verbosity" "minimal" "--verify-no-changes"`

When sending `--fix`, we get what seems like should be the correct command, but doesn't work:
`dotnet "format" "hello/Hello.csproj" "--verbosity" "minimal" "--verify-no-changes" "false"`

To correctly run "fix" with dotnet format, it seems like we need to completely remove the argument like:
`dotnet "format" "hello/Hello.csproj" "--verbosity" "minimal"`

### Expected Behavior

When running an nx command like `npx nx run hello:lint --fix`, the dotnet format should not run "verify-no-changes" so that the files are written with the fixes needed.

### Github Repo

https://github.com/flippidippi/nx-dotnet-verify-no-changes

### Steps to Reproduce

1. `npm i`
2. `npx nx run hello:lint --fix`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : linux-x64
   npm    : 9.8.1
   
   nx             : 17.0.2
   @nx/js         : 17.0.2
   @nx/workspace  : 17.0.2
   @nx/devkit     : 17.0.2
   @nrwl/tao      : 17.0.2
   typescript     : 5.2.2
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core : 2.1.1
```

### nx.json

```json
{
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": false
    }
  },
  "extends": "nx/presets/npm.json",
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "cache": true,
      "dependsOn": [
        "^build"
      ]
    },
    "lint": {
      "cache": true
    },
    "test": {
      "cache": true
    },
    "e2e": {
      "cache": true
    }
  },
  "plugins": [
    "@nx-dotnet/core"
  ]
}
```

### Failure Logs

```shell
> nx run hello:lint --fix

Executing Command: dotnet "format" "hello/Hello.csproj" "--verbosity" "minimal" "--verify-no-changes" "false"
/home/flippidippi/Documents/Work/nx-dotnet-verify-no-changes/org/hello/Program.cs(4,37): error WHITESPACE: Fix whitespace formatting. Delete 1 characters. [/home/flippidippi/Documents/Work/nx-dotnet-verify-no-changes/org/hello/Hello.csproj]
 >  NX   dotnet execution returned status code 2
   Pass --verbose to see the stacktrace.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target lint for project hello (8s)
 
         With additional flags:
           --fix=true
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
```

**Comment by zagros** [comment]
@AgentEnder 

I still get the same issue

![image](https://github.com/nx-dotnet/nx-dotnet/assets/157666/69c847d1-32a8-40e7-9d18-dc1f00100fe6)

doesn't look like it's fixed
