### ISSUE TITLE
[BUG] Please re-open https://github.com/nx-dotnet/nx-dotnet/issues/797 or fix permanently

### ISSUE THREAD

**Issue by zagros** [nx-dotnet/nx-dotnet#807]
### Current Behavior

Version 2.1.2 meant to fix an issue that's still happening

https://github.com/nx-dotnet/nx-dotnet/issues/797

Please reopen this issue

### Expected Behavior

Expect to have the error in the bug fixed but problem still persists.  Instructions are both provided at the bottom https://github.com/nx-dotnet/nx-dotnet/issues/797 and also on this commit  https://github.com/nx-dotnet/nx-dotnet/pull/802

### Steps to Reproduce

1.
Please see the screenshots at the bottom of this page:
https://github.com/nx-dotnet/nx-dotnet/issues/797

### Nx Report

```shell
Please see the screenshot at the bottom of this ticket:
https://github.com/nx-dotnet/nx-dotnet/issues/797
```

### nx.json

```json
not applicable - screenshot at the bottom of the ticket should be sufficient
https://github.com/nx-dotnet/nx-dotnet/issues/797
```

**Comment by AgentEnder** [comment]
Are you passing --fix to the command? I don't see it in your screenshots

**Comment by zagros** [comment]
thanks for the response @AgentEnder  - good question

so basically when following the instructions out of the box [on this page](https://www.nx-dotnet.com/docs/core), the project.json that gets made just reads as follows (this is with 2.1.2 release btw):

![image](https://github.com/nx-dotnet/nx-dotnet/assets/157666/62f4c048-4214-4f7b-9120-9786893fd0fa)


and when you run the lint task you get that error that we are discussing in these threads - so in my screenshot above I had patched the Object.assign() and just remove the line you had added in that commit -- However that's not a viable fix, so what I ended up doing so that every member on the team can work on the project was made my project.json that was made out of the box to look like this for now - besides this fix false below, I didn't do anything else compared to out of the box behaviour in that tutorial above


![image](https://github.com/nx-dotnet/nx-dotnet/assets/157666/b309e1af-72f0-4eb2-9409-a0f2b68cbf43)

**Comment by AgentEnder** [comment]
So that's expected behavior then. By default the linter will report misformatted code, and fail. To fix it you should run once with --fix and commit the results, or format your files with dotnet format manually.

**Comment by zagros** [comment]
i see - ok so I think we can mark it closed then - we add the "fix" : true" to options in project.json after seeding any new project

**Comment by AgentEnder** [comment]
I wouldn't recommend specifying fix true in project.json, as you wouldn't catch misformatted code on CI that way
