### ISSUE TITLE
[Feature] Replace `Swashbuckle.AspNetCore` with `NSwag`

### ISSUE THREAD

**Issue by sharky98** [nx-dotnet/nx-dotnet#819]
**Is your feature request related to a problem? Please describe.**
[`Swashbuckle.AspNetCore`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) has not been touched for over a year now and [does not support .NET 8.0](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2725). Even the official docs were updated to [flag this issue](https://github.com/dotnet/AspNetCore.Docs/issues/31437).

**Describe the solution you'd like**
There seems to be an alternative that is actively maintained, [`NSwag`](https://github.com/RicoSuter/NSwag). The solution would be to update `@nx-dotnet` to use `NSwag` (or allow it under some configuration/flag) instead of `Swashbuckle.AspNetCore`

**Describe alternatives you've considered**

**Additional context**

**Comment by nithinbandaru1** [comment]
Hi just came accross this. You should add it in https://github.com/dotnet/aspnetcore according to https://github.com/dotnet/templates?tab=readme-ov-file

**Comment by AgentEnder** [comment]
I'd be open to a PR to handle this in our generators, but I don't have time to invest to do it myself right now.

**Comment by sharky98** [comment]
@nithinbandaru1 I agree the template themselves should be managed by the `dotnet` templates directly. I was thinking more about the generators that uses the `swagger` command line. So I think this affect those: `@nx-dotnet/core:swagger-typescript`, `@nx-dotnet/core:update-swagger`, `@nx-dotnet/core:add-swagger-target` and `@nx-dotnet/core:openapi-codegen`

**Comment by AgentEnder** [comment]
I'm going to close this out for now - the swashbuckle stuff supports .NET 8 now which is brilliant. If this comes up again I'd sooner update out update-swagger executor to pull the swagger json based on a running API rather than deal with trying to swap it out for another tool altogether, as that would insulate us from this kind of breakage in the future.
