### ISSUE TITLE
[Feature] Build A solution file instead of csproj.

### ISSUE THREAD

**Issue by matanrak** [nx-dotnet/nx-dotnet#821]
I have a project with multiple plugins, each has a csproj. I want to build them all using a solution file thats found in the plugins directory and not one by one, is that possible?

**Comment by matanrak** [comment]
BUmp

**Comment by AgentEnder** [comment]
I'd generally recommend not building via the solution file, as going that route you aren't taking advantage of Nx's cache for the individual plugin builds. Instead, you can do something like `nx run-many -t build` to build them all instead of one by one.
