### ISSUE TITLE
[BUG] changes in test command execution

### ISSUE THREAD

**Issue by Den-dp** [nx-dotnet/nx-dotnet#829]
### Current Behavior

after migration to 2.2.0 I see 2 issues:
* running tests now leads to running a build
2.1.2
![image](https://github.com/nx-dotnet/nx-dotnet/assets/1770529/7d310514-ec20-4527-918f-079fbc7ee943)
2.2.0
![image](https://github.com/nx-dotnet/nx-dotnet/assets/1770529/a5a48420-f435-43ac-86f6-eccfd95f88c2)

* after the build I see that the test target is getting stuck and can't be stopped using Ctrl+C (might be powershell specific)
![image](https://github.com/nx-dotnet/nx-dotnet/assets/1770529/a1bb71a0-522e-49a6-abe6-0bd2dbed33fd)
 

### Expected Behavior

* `nx test` must run `dotnet test` but not `dotnet build + dotnet test` (not 100% sure this is right, but this is how it was early)
* `nx test` must not stuck

### Steps to Reproduce

```sh
# generate empty workspace
npx create-nx-workspace@latest nxdotnet --preset=empty --workspaceType=integrated --ci=skip
cd nxdotnet
# install previous release of nx-dotnet
npx nx add @nx-dotnet/core@2.1.2
# generate library
npx nx g @nx-dotnet/core:library --name=foo-lib --language=C# --testTemplate=nunit --template=classlib --pathScheme=nx
```
2.1.2 test target behavior
```sh
> npx nx test foo-lib-test

> nx run foo-lib-test:test

Executing Command: dotnet "test" "C:\temp\nxdotnet\foo-lib-test\Nxdotnet.FooLib.Test.csproj" "--blame" "false" "--blame-crash" "false" "--blame-crash-collect-always" "false" "--blame-hang" "false"
  Determining projects to restore...
  Restored C:\temp\nxdotnet\foo-lib-test\Nxdotnet.FooLib.Test.csproj (in 147 ms).
  1 of 2 projects are up-to-date for restore.
  Nxdotnet.FooLib -> C:\temp\nxdotnet\dist\foo-lib\net7.0\Nxdotnet.FooLib.dll
  Checking module boundaries for foo-lib
  CONFIGURED undefined
  Nxdotnet.FooLib.Test -> C:\temp\nxdotnet\dist\foo-lib-test\net7.0\Nxdotnet.FooLib.Test.dll
  Checking module boundaries for foo-lib-test
  CONFIGURED undefined
Test run for C:\temp\nxdotnet\dist\foo-lib-test\net7.0\Nxdotnet.FooLib.Test.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
Data collector 'Blame' message: System.IO.FileNotFoundException: Collect dump was enabled but no dump file was generated.
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.GetDumpFiles(Boolean warnOnNoDumpFiles, Boolean processCrashed)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.SessionEndedHandler(Object sender, SessionEndEventArgs args).

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 24 ms - Nxdotnet.FooLib.Test.dll (net7.0)

 ———————————————————————————

 >  NX   Successfully ran target test for project foo-lib-test (7s)
```

```sh
# migrate to 2.2.0
npx nx migrate @nx-dotnet/core@latest
npm i
```

2.2.0 test target behavior
```sh
> npx nx test foo-lib-test

   √    1/1 dependent project tasks succeeded [0 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 —————————————————————


> nx run foo-lib-test:build

Executing Command: dotnet "--version"
7.0.312
Executing Command: dotnet "build" "C:\temp\nxdotnet\foo-lib-test\Nxdotnet.FooLib.Test.csproj" "--configuration" "Debug" "--no-dependencies" "--verbosity" "minimal"
MSBuild version 17.6.10+2679cf5a9 for .NET
  Determining projects to restore...
  Restored C:\temp\nxdotnet\foo-lib-test\Nxdotnet.FooLib.Test.csproj (in 147 ms).
  1 of 2 projects are up-to-date for restore.
  Nxdotnet.FooLib.Test -> C:\temp\nxdotnet\dist\foo-lib-test\net7.0\Nxdotnet.FooLib.Test.dll
  Checking module boundaries for foo-lib-test
  CONFIGURED undefined

Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:02.09

> nx run foo-lib-test:test

HERE WE STUCK
```

### Nx Report

```shell
> npx nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : win32-x64
   npm    : 9.9.2

   nx             : 18.0.4
   @nx/js         : 18.0.4
   @nx/workspace  : 18.0.4
   @nx/devkit     : 18.0.4
   @nrwl/tao      : 18.0.4
   typescript     : 5.3.3
   ---------------------------------------
   Community plugins:
   @nx-dotnet/core : 2.2.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "namedInputs": {
    "default": [
      "{projectRoot}/**/*",
      "sharedGlobals"
    ],
    "production": [
      "default"
    ],
    "sharedGlobals": []
  },
  "plugins": [
    "@nx-dotnet/core"
  ]
}
```

**Comment by mrfelton** [comment]
Problem is though, that previously we could use noBuild option to prevent build happening prior to running the tests. But now there is no way to do that since the build is a task dependency and there is no way to skip task dependencies that I'm aware of.

This is a problem, because building is slow. Even with a cached build, it's slow to determine that no build needs to happen. We have a monorepo with 100+ projects and with the latest version running `nx test` on a single project can result in a huge amount of time running the build target across all of the dependencies, even if every single one has a cached build. It adds minutes onto a simple single project test run.

**Comment by AgentEnder** [comment]
You can opt out of it by setting `dependsOn: []` in the project.json test target, or in target defaults in nx.json.

It shouldn't be adding minutes, as determining cache hits should be fast (especially if daemon is active). If its taking minutes, I'd advise opening an issue on the main Nx repo as that's certainly not the goal.

**Comment by mrfelton** [comment]
I think the slowness issue is this https://github.com/nrwl/nx/issues/19627. Setting `NX_DAEMON=false` gets the cache processing back to a reasonable speed (improves by a couple of orders of magnitude)

**Comment by AgentEnder** [comment]
This should be resolved, and if someone wants to opt out there's a new nx flag `--exclude-task-dependencies` to opt out of the depends on on a per-command level..
