### ISSUE TITLE
[BUG] *.WapProj not found

### ISSUE THREAD

**Issue by elvince** [nx-dotnet/nx-dotnet#846]
### Current Behavior

 Our Wapproj (windows app installer project) can't be built & found by nx;

### Expected Behavior

The project should be managed like any other type of .net project type

### Steps to Reproduce

1. Create a solution
2. Create a windows exe appllicatin
3. create a windows app installer
4. Try to build the installer with nx build command

### Nx Report

```shell
Report complete - copy this into the issue template

Node   : 20.9.0
OS     : win32-x64
npm    : 10.1.0

nx                 : 18.0.8
@nx/js             : 18.0.8
@nx/linter         : 18.0.8
@nx/eslint         : 18.0.8
@nx/workspace      : 18.0.8
@nx/devkit         : 18.0.8
@nx/eslint-plugin  : 18.0.8
@nx/react          : 18.0.8
@nrwl/tao          : 18.0.8
@nx/vite           : 18.0.8
@nx/web            : 18.0.8
typescript         : 5.3.3
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.2.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "namedInputs": {
    "default": ["{projectRoot}/**/*", "sharedGlobals"],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/.eslintrc.json",
      "!{projectRoot}/eslint.config.js",
      "!{projectRoot}/cypress/**/*",
      "!{projectRoot}/**/*.cy.[jt]s?(x)",
      "!{projectRoot}/cypress.config.[jt]s"
    ],
    "sharedGlobals": []
  },
  "plugins": [
    {
      "plugin": "@nx/vite/plugin",
      "options": {
        "buildTargetName": "build",
        "previewTargetName": "preview",
        "testTargetName": "test",
        "serveTargetName": "serve",
        "serveStaticTargetName": "serve-static"
      }
    },
    {
      "plugin": "@nx/eslint/plugin",
      "options": {
        "targetName": "lint"
      }
    },
    "@nx-dotnet/core"
  ],
  "generators": {
    "@nx/react": {
      "application": {
        "babel": true,
        "style": "scss",
        "linter": "eslint",
        "bundler": "vite"
      },
      "component": {
        "style": "scss"
      },
      "library": {
        "style": "scss",
        "linter": "eslint"
      }
    }
  },
  "defaultBase": "master"
}
```

### Additional Information

If you look at the glob pattern, it can't find this type of file:
https://github.com/nx-dotnet/nx-dotnet/blob/84f35f133e35b1aa60b66d183bf8a3b50db6517a/packages/utils/src/lib/utility-functions/glob.ts

Could you please fix this ?

In the mean time, is there any way to for the project name?

thanks

**Comment by AgentEnder** [comment]
Does `dotnet build` work with wapproj projects?

**Comment by elvince** [comment]
> Does `dotnet build` work with wapproj projects?

I'm not an expert in wapproj.
I managed to built it with msbuild but as of now no success with dotnet build.
It seems that he can't import "Microsoft.DesktopBridge.props" project.

I have no clue why... 

So we may not have to update your code, if dotnet build can't built it.
Does this plug-in allow to build with msbuild directly?

**Comment by AgentEnder** [comment]
No, this project is for .NET Core / 5+ projects, which can thusly be built with the dotnet CLI. 

I'd recomend adding a project.json and using `command` to register your Nx targets, but you'll also need to track the dependencies for that project.
