### ISSUE TITLE
[BUG] targetDefaults in nx.json doesn't work

### ISSUE THREAD

**Issue by maxisam** [nx-dotnet/nx-dotnet#848]
### Current Behavior

I am trying to use nx crystal in nx 18. I tried to add options in nx.json but it doesn't work. However, if I move the same options to project.json, it works fine. Not sure if this is a bug or I misunderstand how targetDefault works.

### Expected Behavior

targetDefaults should work in nx.json as targets in project.json

### Github Repo

https://github.com/Sam-Lin-MillersLab/nx-dotnet-test

### Steps to Reproduce

see the commit message in the repo

### Nx Report

```shell
Node   : 20.12.0
OS     : win32-x64
yarn   : 1.22.22

nx (global)    : 16.6.0
nx             : 18.2.4
@nx/js         : 18.2.4
@nx/workspace  : 18.2.4
@nx/devkit     : 18.2.4
@nrwl/tao      : 18.2.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.2.0
```

### nx.json

```json
{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "main",
  "targetDefaults": {
    "build": {
      "cache": true,
      "dependsOn": ["^build"]
    },
    "lint": {
      "cache": true,
      "options": {
        "fix": true,
        "fixWhitespace": true,
        "fixStyle": "warn",
        "fixAnalyzers": "warn",
        "report": "./.reports",
        "verbosity": "diagnostic"
      }
    }
  },
  "plugins": ["@nx-dotnet/core"]
}
```

### Additional Information

Nx AI Assistant doesn't help in this case as well

**Comment by AgentEnder** [comment]
This should be fixed in latest Nx versions
