### ISSUE TITLE
dotnet format is in dotnet sdk since dotnet 6

### ISSUE THREAD

**Issue by maxisam** [nx-dotnet/nx-dotnet#849]
https://github.com/nx-dotnet/nx-dotnet/blob/84f35f133e35b1aa60b66d183bf8a3b50db6517a/packages/core/src/executors/format/executor.ts#L76-L88

Question about this, 

I wonder if we need this for dotnet version >= 6

according to the doc, dotnet format should be included

```ts
  if (forceToolUsage || majorVersion < 6) {
    ensureFormatToolInstalled(context, dotnetClient, majorVersion);
  }
```

based on above logic, it seems like only dotnet 6.0.0 - 6.0.203 or dotnet <6 might run it.

**Comment by AgentEnder** [comment]
For .NET 6 - 6.203 or whatever there was a bug where we had to still use the tool

**Comment by maxisam** [comment]
Thanks for explanation.

I guess this is not needed. Original I was wonder if I need to add dotnet 8. Now I think we don't even need 7 here.

```
else if (majorVersion === 7) {
    dotnetClient.installTool(
      'dotnet-format',
      '7.*',
      'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json',
    );
  }
```

**Comment by AgentEnder** [comment]
IIRC there was a different bug with earlier versions of the built in tool in the .NET 7 releases, after that was fixed I may have cleaned up when it would be required.
