### ISSUE TITLE
How to enforce module boundaries with Nx 18+ crystal/inference 

### ISSUE THREAD

**Issue by mcarey1590** [nx-dotnet/nx-dotnet#858]
I am creating a new NX repo with all .Net projects and in the past the module boundaries were defined using tags that were set in a project.json file. With the latest version there are no project.json files being generate so I am unsure on how to define module boundaries. Can someone point me in the right direction here?

**Comment by mcarey1590** [comment]
Looks like I can still create the project.json file and set the tags and it will merge with the inferred configuration

**Comment by AgentEnder** [comment]
Yeah, the proper path to specify tags manually is to create a project.json and throw em in there
