### ISSUE TITLE
[BUG] It doesn't recognize `global.json` file.

### ISSUE THREAD

**Issue by osnoser1** [nx-dotnet/nx-dotnet#86]
**Describe the bug**
The project doesn't run with the specific sdk specified in the `global.json` file.

**To Reproduce**

1. Create a project with net core 2 or 3.
2. Run the project with `nx serve [project-name]`.
3. You will see a warning saying info about the support of a previous version to current.

**Expected behavior**
It should run the project with the specified version in `global.json` file.

**Screenshots**
![image](https://user-images.githubusercontent.com/1179744/130330010-ecf7bd86-54e5-453b-82db-c311a6e9045d.png)

**Environment:**

- OS: Windows 11
- Browser [e.g. chrome, safari]: Not apply.
- Version: Not apply.
- Affected Packages: Not apply.

**Comment by osnoser1** [comment]
I had to move the `global.json` file to the root project.
Is this the expected behavior?

**Comment by AgentEnder** [comment]
Huh, I had not considered that behavior, but it makes sense that it only picks up the root. `dotnet` crawls up the filetree looking for `global.json`, but it starts at cwd instead of the the location of the csproj. I'll get  a patch out for this.

**Comment by AgentEnder** [comment]
I would like to note though, that it does make sense for each project in the same repository to use the same dotnet sdk version, just to make it a cleaner dev + upgrade experience. This is similar to single version principle. I'm fixing this, as it will still work with global.json at root. I would recommend leaving it at root, and only overriding it at the project level if needed.
