### ISSUE TITLE
[Question] dotnet watch

### ISSUE THREAD

**Issue by osnoser1** [nx-dotnet/nx-dotnet#87]
I've a question.

Why it doesn't use the `dotnet watch run` command to run the project instead of `chokidar`?

Using dotnet give the command the responsibility for refresh the project, and it could remove a dependency.

**Comment by AgentEnder** [comment]
Honestly, the reasoning is just that I was unaware that `dotnet watch run` would refresh the projects when there was a change in the dependencies (i.e. if `nx serve my-api` was ran with `dotnet watch run my-api.csproj`, I thought that changing `my-lib` may not cause the serve to relaunch. I think I am mistaken in this though, I'll check and if I was wrong I'll get it swapped over.
