### ISSUE TITLE
[Feature] Add optional configuration to specify which csproj to use

### ISSUE THREAD

**Issue by gabbelobo** [nx-dotnet/nx-dotnet#878]
**Is your feature request related to a problem? Please describe.**
To my understanding of the code, it is not possible to have multiple `.csproj` files in the same project. In the `findProjectFileInPath`, the plugin throws the `More than one build-able projects are contained within the project's source directory!` error if it finds more than one. 

This way, projects with multiple `.csproj` files (like a clean code architecture implementation) can't be built using this plugin.

Clean code file structure example:
```
MyApp
|_ src
    |_ MyApp.Application
        |_ MyApp.Application.csproj
    |_ MyApp.Domain
        |_ MyApp.Domain.csproj
    |_ MyApp.Infrastructure
        |_ MyApp.Infrastructure.csproj
    |_ MyApp.WebApi
        |_ MyApp.WebApi.csproj
MyApp.sln
```
**Describe the solution you'd like**
An optional configuration to specify which `.csproj` to use when building the project. 

**Describe alternatives you've considered**
I've tried inputing the file path on the `extraParameters` option to the build configuration to no avail.

**Additional context**
I don't have a lot of experience with dotnet, there may already be a solution to this but I couldn't find it on the internet.

**Comment by AgentEnder** [comment]
They can, but they should be different nx projects - you don't get a ton of benefit from the top level MyApp and src folders in this layout.

At the end of the day one csproj is what's being ran, the other .csproj are **_already_** multiple C# projects and we enforce that C# projects are 1:1 with Nx projects to ensure folks get the most benefits.
