### ISSUE TITLE
[BUG] Dependencies error when attempting to run tests on a clean checkout

### ISSUE THREAD

**Issue by jon-hall** [nx-dotnet/nx-dotnet#880]
### Current Behavior

When checking out our monorepo, installing dependencies and trying to run the tests for any of our dotnet packages we get an error about missing dll's, something like:

> CSC : error CS0006: Metadata file '/\<path to repo\>/dist/intermediates/packages/shared/obj/net8.0/ref/Shared.dll' could not be found [/\<path to repo\>/packages/shared.Test/Shared.Test.csproj]

This appears to be the same issue as reported under #820, and we're currently using the "fix" suggested in that issue of setting `"noDependencies": false` on all of our dotnet packages - but this isn't an ideal solution as it's now building more than it needs to.

### Expected Behavior

Things should build and run from a clean checkout without errors, even when `"noDependencies"` is set to true/not specified in the build target for a package.

### Github Repo

https://github.com/jon-hall/nx-dotnet-issue-repro

### Steps to Reproduce

1. See README in reproduction repo

### Nx Report

```shell
Node   : 21.6.1
OS     : darwin-arm64
npm    : 10.2.4

nx (global)    : 19.5.3
nx             : 19.5.3
@nx/js         : 19.5.3
@nx/workspace  : 19.5.3
@nx/devkit     : 19.5.3
@nrwl/tao      : 19.5.3
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
---------------------------------------
Community plugins:
@nx-dotnet/core : 2.4.0
```

### nx.json

```json
{
  "pluginsConfig": {
    "@nx/js": {
      "analyzeSourceFiles": false
    }
  },
  "extends": "nx/presets/npm.json",
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "plugins": [
    "@nx-dotnet/core"
  ]
}
```

### Failure Logs

```shell
➜  nx-dotnet-issue-repro git:(main) nx test shared.test --skip-nx-cache

> nx run shared.test:build

Executing Command: dotnet "--version"
8.0.302
Executing Command: dotnet "build" "<path to repo>/nx-dotnet-issue-repro/packages/shared.Test/Shared.Test.csproj" "--configuration=Release" "--no-dependencies" "--no-restore" "--verbosity=minimal"
CSC : error CS0006: Metadata file '<path to repo>/nx-dotnet-issue-repro/dist/intermediates/packages/shared/obj/net8.0/ref/Shared.dll' could not be found [<path to repo>/nx-dotnet-issue-repro/packages/shared.Test/Shared.Test.csproj]

Build FAILED.

CSC : error CS0006: Metadata file '<path to repo>/nx-dotnet-issue-repro/dist/intermediates/packages/shared/obj/net8.0/ref/Shared.dll' could not be found [<path to repo>/nx-dotnet-issue-repro/packages/shared.Test/Shared.Test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.51

 NX   dotnet execution returned status code 1

Pass --verbose to see the stacktrace.


———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 NX   Ran target test for project shared.test and 1 task(s) they depend on (938ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]
```

**Comment by AgentEnder** [comment]
Hey @jon-hall - I believe the issue here is coming from the build target in https://github.com/jon-hall/nx-dotnet-issue-repro/blob/main/packages/shared.Test/project.json specifying an empty depends on array. It should depend on its dependencies builds. 

Can you confirm how that line ended up in there? I've checked and we don't set it to an empty array.

**Comment by jon-hall** [comment]
Hi, thanks for the quick response - the empty depends on was something we had in our project.json configs from when we originally set our monorepo up a couple of years back.

Everything worked fine with that setup prior to us recently updating to 2.x of nx-dotnet, but this does look like it's just misconfiguration on our end because I don't believe we actually need those empty depends arrays.

I'll go and update our code to remove the dependency arrays and validate that everything is fine and our builds work as expected - I'll close this issue then if that does turn out to be the case.

Thanks again for looking into it and my apologies if it was just bad config by us.

**Comment by jon-hall** [comment]
Looks like everything is fine now we've removed those empty `dependsOn` arrays - thanks very much for identifying our issue and apologies for the confusion.
